apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/applications/vault.yaml
  - resources/applications/external-secrets.yaml
  - resources/applications/jenkins.yaml
  - resources/applications/harbor.yaml
  - resources/applications/postgres.yaml
  - resources/applications/redis.yaml
  - resources/applications/rabbitmq.yaml
  - resources/applications/kong.yaml
  - resources/applications/cluster-configs.yaml
  - resources/applications/frontend.yaml
  - resources/applications/account-service.yaml
  - resources/applications/auth-service.yaml
  - resources/applications/notification-service.yaml
  - resources/applications/transfer-service.yaml

namespace: argocd
