apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor
        property: admin-password
    - secretKey: secret
      remoteRef:
        key: harbor
        property: core-secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: harbor
        property: jobservice-secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: harbor
        property: registry-secret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: harbor
        property: postgres-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: harbor
        property: redis-password
    - secretKey: secretKey
      remoteRef:
        key: harbor
        property: csrf-key
    - secretKey: tls.key
      remoteRef:
        key: harbor
        property: tls-key
    - secretKey: tls.crt
      remoteRef:
        key: harbor
        property: tls-crt
