apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: secret/harbor
        property: admin-password
    - secretKey: secret
      remoteRef:
        key: secret/harbor
        property: core-secret
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: secret/harbor
        property: jobservice-secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: secret/harbor
        property: registry-secret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/harbor
        property: postgres-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/harbor
        property: redis-password
