expose:
  type: ingress
  tls:
    enabled: true
    secretName: harbor-tls-secret
  ingress:
    hosts:
      core: harbor.local
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "harbor-issuer"
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
