expose:
  type: clusterIP
  tls:
    enabled: false

externalURL: https://harbor.local

existingSecretAdminPassword: harbor-secrets
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

core:
  existingSecret: harbor-secrets
  xsrfKey: "unused-but-required" # Helm check, actual value from harbor-secrets

jobservice:
  existingSecret: harbor-secrets

registry:
  existingSecret: harbor-secrets

database:
  internal:
    existingSecret: harbor-secrets

redis:
  internal:
    existingSecret: harbor-secrets

trivy:
  existingSecret: harbor-secrets
