expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.local
    className: "nginx"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
