---
# Source: transfer-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  labels:
    app: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: "harbor.local/banking-demo/transfer-service:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          env:
            - name: REDIS_URL
              value: "redis://redis.data.svc.cluster.local:6379/0"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-postgresql-ha-pgpool.data.svc.cluster.local:5432/banking"
