---
# Source: postgresql-ha/templates/pgpool/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql-ha-pgpool
  namespace: "data"
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 4.5.4
    helm.sh/chart: postgresql-ha-14.3.10
    app.kubernetes.io/component: pgpool
type: Opaque
data:
  admin-password: "c1o5Rnd4T0lNcg=="
