---
# Source: postgresql-ha/templates/pgpool/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-postgresql-ha-pgpool
  namespace: "data"
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 4.6.3
    helm.sh/chart: postgresql-ha-16.3.2
    app.kubernetes.io/component: pgpool
type: Opaque
data:
  admin-password: "a1dQcFRGYVBJeA=="
  sr-check-password: "OGtrMU1tc09pSQ=="
