---
# Source: common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  labels:
    app: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: "harbor.local/banking-demo/transfer-service:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            {}
