apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-jenkins-secret
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-jenkins-secret
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-password
      remoteRef:
        key: secret/jenkins
        property: jenkins-admin-password
    - secretKey: jenkins-admin-user
      remoteRef:
        key: secret/jenkins
        property: jenkins-admin-user
