apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kong/templates/admission-webhook.yaml
  - kong/templates/controller-rbac-resources.yaml
  - kong/templates/controller-service-metrics.yaml
  - kong/templates/deployment.yaml
  - kong/templates/service-account.yaml
  - kong/templates/service-kong-manager.yaml
  - kong/templates/service-kong-proxy.yaml
