apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-redis-secret
  data:
  - secretKey: redis-password
    remoteRef:
      key: secret/data/redis
      property: redis-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-postgres-secret
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/postgres
      property: password
  - secretKey: repmgr-password
    remoteRef:
      key: secret/data/postgres
      property: repmgr-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-rabbitmq-secret
  data:
  - secretKey: rabbitmq-password
    remoteRef:
      key: secret/data/rabbitmq
      property: rabbitmq-password
  - secretKey: rabbitmq-erlang-cookie
    remoteRef:
      key: secret/data/rabbitmq
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-secret
  namespace: jenkins
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-jenkins-secret
  data:
  - secretKey: jenkins-admin-password
    remoteRef:
      key: secret/data/jenkins
      property: jenkins-admin-password
