---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRQVNYMk8xMnFGSkRZemNpY1RJVnRDVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5ESXlNRGhhRncwegpOakEwTURreE5ESXlNRGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxNkZNZzN5QlJCL0FYbDVRWDVYeWRBN2dvdzIKN05uMjBzdDdDaWlqeFZObGl4U2VxZFNjQzh3dzVHb2p5TGhPVDEra014ZlBGa2tSWXRwVnY1ZFVlMXZpOW1FNQpEcDRrK0dBTUFMOWJJSGk2WU1XNVRpR3U1d0syN3gwbEdMV1ovMjV6TzBEUDBpbGkwZmhxM2lONC9WdzZTWXdkClRxM1l1VGlCUEhOUmNIZGdac2d6Wk90Sk5acWNTUWNTc21pci9DTDhEendKMzdyN3pVZUtBZGN4aU53K0s5dFgKakF4ZUUyalZySnpmTW5NVjRXdkxkcGVJUXk4YVRScFZoUW1NcGwxKyt0b3ZwQkI5VVBJSnJIQTlJR3hvdTY3TgpvQkRLOWh1MlhHcHd2ZGIyd2VRR2I1dFRRejJkc1ZwSkRNZVhtbzBBS3ZoYzN2VlpWSmhac0kxTmpRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDKzlHZG9jMHZ5eUFFVldObjlrSThObwpIUXpITUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBMlhheEdTWW5vK25RdEhJeHZ6WmJkR012bEdva2lYRG5pCllqbm5paDQwZUtEanBhbTVGT3RodUtoYmtDQUdQME5QU0w0bG5KWmF4WmxxV1FUbWdSdkYrK0tsUHI3ZFNIVGgKVzVvaVN3TmY0YU9hTGJKa0lFdFpCMEl0ZDhoOVpUQjhRK3ljays5U1h6ODMyZSt0NHRVOGJ0ZG5DV2U4dUtiLwoxbmw5bUJHa2Z6d3pMTzUzSjZmTXd1R3kwZjdUeisrSTJoYWkzL1BjUzN4K2ZGdWw0UUdKUVF6UG13ems2bXFhCkc1Wnc4OWJVc1l4MUQvV2NBQlRuZHdSbkpjQTEwOHgxYnB2TExoRzhTbitxRFdvWkJRdGJ1SmE0cndGNGF0Vm0KaVJpa1Q1TWp1RmRnY29TanJQbll5d3EvRUpQSzlERXlXaE9Rc1hVbm8vUlRqZmVCSmxDcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdzE2Rk1nM3lCUkIvQVhsNVFYNVh5ZEE3Z293MjdObjIwc3Q3Q2lpanhWTmxpeFNlCnFkU2NDOHd3NUdvanlMaE9UMStrTXhmUEZra1JZdHBWdjVkVWUxdmk5bUU1RHA0aytHQU1BTDliSUhpNllNVzUKVGlHdTV3SzI3eDBsR0xXWi8yNXpPMERQMGlsaTBmaHEzaU40L1Z3NlNZd2RUcTNZdVRpQlBITlJjSGRnWnNnegpaT3RKTlpxY1NRY1NzbWlyL0NMOER6d0ozN3I3elVlS0FkY3hpTncrSzl0WGpBeGVFMmpWckp6Zk1uTVY0V3ZMCmRwZUlReThhVFJwVmhRbU1wbDErK3RvdnBCQjlVUElKckhBOUlHeG91NjdOb0JESzlodTJYR3B3dmRiMndlUUcKYjV0VFF6MmRzVnBKRE1lWG1vMEFLdmhjM3ZWWlZKaFpzSTFOalFJREFRQUJBb0lCQUFoSjc5TytWTGpUU05ncQpxN0xVSmV4WmlkVFJseGo0Ykdqb0dpbkZyS0VZRnpSTjVTZG1ibEp2ME5rNENabWYvQzZRNjdvQk5oZUhkUlhoCkZvZEE1K1F0ODFTcHJrNkk5aCtWajV6T2daTEFuSU96ajllWlJUN20xaFVTQXZ0bjVRYzV5K2pGS0t3TmRuUmIKR2ttZmJxZ3RMQW5ueUd5SW9xdkZFbkthbitkcURpQUtKTjlUaVIvWHR3aTZ6RGNXaHo0bHcvS0ZvWHlqUTdDNQo4c3VqN2ZJR0tzQ1EwZlVNRFoySmNVTnJnMUZ5MzhWeG5ic29wQUxid3hONEV6TFZjTzZGSzZwWlZnNjRVb0VXCklydG8rbHhPRURVK0NOSEgxMGU3cXBveGt3T1ZQZk8wQnpYdWg5Wi8vWi9GUnd1ZUJLalhYY1lVQWlINjNMdmgKLzQ4SVROOENnWUVBOC9wQkVhc0xTSENHamd2UCtsbXpjdmFiYUJ6NVJ0SUcwbVNUcTQyMURCU0lyT2RmSUVwSwpPSy9JSnBlY08xaUlwR3lqMWJGaFRhai9kOGZaV1paVStnRDlJZi9UUGc1OVBRdVJBNmFjaWZXZWtZN0t6ZWFKCmNERFBkRjU5c1JXSlpmT0tFbnU1akFTYTVLK1JjUU00c0JpSHFmYzZMbnBoNkJ1Q0FjQmFqZDhDZ1lFQXpQOFUKQWJCREh1Tkt3YVJsRnNxMndlbkZFbUN3OS9nTFVsVzVOUDIyQUtGNTcyTXZEeXcyamFaZmVJc2FRbkhud0w2NQpObmhZYXMwSGkyUEZ4NEhSNnl5MXBoVUpaR1BlVy80TzNqTElvR2VyVUN4RkZMQUg0TjBPaWtlUWVjTVNYSSsrCjZsWEdvNUNYOEdpdWU1dmxzMTBCcExKYjRKaFIwcWdDamN2WCtoTUNnWUFoMVJJdzRRY3ZoR3NrUjM4UHVHQ3EKRUloOFo0Z3B5ZllvTnNwRGYrTWJTYjJxUEd0MGp0aThBNlE5dGNoMGNsS0FlcEE5a2R0c2FZTURtVE1LdVU0UApYUk85SXp5bjNscC9uSnIvWnB0T2hrRDI3bFl4TjBiWHgrejh0aDIzOE1TYzNxakc1MkZUaVUveFptZEV4SzJYCnZjOFNRclpPdTZuWUJmaUJSYXRKQVFLQmdIV1RsQkVIM09lWmJDWTJ1VGhpV29KTUo1bEwxaFRUc3dLdFlrWHYKZ3ZWSHFKMVNJUXF0ekRoZ2hYK3BJUTJkTVZTT3o4SmJNak5IbDUwdVE2RVRaNmhnZzJ0WHc0Uk45NXFCMUZ0RAplMmp0TFFnVjdDVmFkWnBXaitGbC9JcXFCUjBMNFcrY2RRc1pndHdEM3BmTktlay9YaEx0cmQ3YTNvdFppK1Z5ClZsVDdBb0dBTVBOYnoxdkpKWUpVenI1ZFBJNnRJL0dRZDY0dVB1QldBRlNWRHlwOGZpaE5KTXJFTmJ3RFA0UisKVmFUS0grZWtkL2o1alU2aldKQ2VJZ1MwTG5EVWNHeHB3aEtPbEY0eXNoOEdzNFREMitDTitXKzFoYWlCQU9ZZQo4T1JMMHcxUkxTUTFhRnB2bVRuVXU3SVlMWUZQSzk2K1dTYUpOSm82YjNWb2hNNVY0azA9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lRVWlteEwvWnZtQkNWK1Z3ZmdXSC9kakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5ESXlNRGhhRncwegpOakEwTURreE5ESXlNRGhhTURBeExqQXNCZ05WQkFNVEpXdHZibWN0YTI5dVp5MTJZV3hwWkdGMGFXOXVMWGRsClltaHZiMnN1YTI5dVp5NXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRDUKWHZwWFY0ZXY2SW10c2E4M0dxbTlCYW9DMitPVThmVUUrM2xLcThsT3pjSkRwN2NEY2pjRC9GVlYvQlJIVUowTwpmVnh4ZVhsZHJnWWQ5MlU4Wm1vWGI5NjZBQWlSTy9PKzNMYm85Rjd5SzhmdUhZMDJKSk1wMWlWemZLcXZsYlE3Cng2T1RxRk16aFJ1YnI5T1lWYzh4WEZwN0o2YUg5Z1NLM0Q2bTB2ZUhWTVRkcTNIbm9PQVh1a1BTQjBtbm1oWU0KanRZVjFhdkxUSkZ3YkRydWFPd3JNM3JXY2JQT0hPQXNWejk2OWdLRFJodkRyUTE3VjJFYmt1aG9ncHpQRzVLeApUY3BzanAzcjVPaWk4MklFc01LbTA4Z3RWZHpWTzZuNVpFeTdQaWtDRTdJellIeko1aVFwWGYrVUMwa0J3RE1YCmNMVVEwanE1cVRUeVNIQXFHVHNkQWdNQkFBR2pnWk13Z1pBd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWQpNQmFBRkMrOUdkb2Mwdnl5QUVWV05uOWtJOE5vSFF6SE1EQUdBMVVkRVFRcE1DZUNKV3R2Ym1jdGEyOXVaeTEyCllXeHBaR0YwYVc5dUxYZGxZbWh2YjJzdWEyOXVaeTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJa2sKMVRrdlcyYVp4ZTJDV1pmZWkxY2lvN1lITE5VRUxBNEdYb1E2cVNQUDRnOFBnNEk0SHlWSVJBYWdBSUxjeGx4bgpDVUc0WGc5MVZDeUYwKzVSOTFvTzVDemplZkhDY0duMVRhbUxsUWx1SCtkbjFjdE1EbXZIQ1NOd0ZwNkNoM3ZoCklFcHRnZnhyRzBsQWZSYjc5MkJRMUpvWE92em1LQ1phU1NzK1lPNStLSzhlaWZONTJTTjhSVUZja3hUWVU4MFAKU0FQOEZ2cEF0SXNBVkU4R3RXdzZtcFVtdnUvOXhONko3T2F3TWxRbHU2YWJLYmJ5dXpPQ3I0Yk5iVmF0YzhWMgorV1ovekdaMGM3dEJZUmQvMzhYUHhpeE1Xb29meXljNUwrTDV2VERWbHlNQnZHM2Y3dDRHVmxCYlYreVpIRWhQCm1pOUlLbHVwaDRFYlBKeXlUVkE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBK1Y3NlYxZUhyK2lKcmJHdk54cXB2UVdxQXR2amxQSDFCUHQ1U3F2SlRzM0NRNmUzCkEzSTNBL3hWVmZ3VVIxQ2REbjFjY1hsNVhhNEdIZmRsUEdacUYyL2V1Z0FJa1R2enZ0eTI2UFJlOGl2SDdoMk4KTmlTVEtkWWxjM3lxcjVXME84ZWprNmhUTTRVYm02L1RtRlhQTVZ4YWV5ZW1oL1lFaXR3K3B0TDNoMVRFM2F0eAo1NkRnRjdwRDBnZEpwNW9XREk3V0ZkV3J5MHlSY0d3NjdtanNLek42MW5HenpoemdMRmMvZXZZQ2cwWWJ3NjBOCmUxZGhHNUxvYUlLY3p4dVNzVTNLYkk2ZDYrVG9vdk5pQkxEQ3B0UElMVlhjMVR1cCtXUk11ejRwQWhPeU0yQjgKeWVZa0tWMy9sQXRKQWNBekYzQzFFTkk2dWFrMDhraHdLaGs3SFFJREFRQUJBb0lCQUROcXBLbnBHNHBHNDBwYgp3bEdWancxeEUwaVRINVhZbktsS0U0eDBwcVYzc2RnaXhzNndXRTBiVkZvT0IzMWJ6d0pMa1VtNVh1K1VuK0RDClg0NklYRlFZUmg5cVBkbjZOMHZ4ZE1wTUJwNmVyZEs0SjZOVC83N216MktFUUNwRGJ2M0xjRHdUL3hHMm5vWm4KaHJTWWJzZlI3N3NJWmlNTzlBbFFsNTlzak1xTFpQay9ET3ZnR1UzYWpsZE9wNmZEck9ZS3lqcUZWU1k2OHJCMQpGLzR3MWxuWWRsTEFXbmNZdW1IWWFJYkUvRDVROG9zNGIyVXQydGlZSXEvVUJMaTFXZVFnMTFxS3J4eW5EcmdTClZ6NkdwM3UrUGQ0alVOcUpTZkgvQkhUUm9yNFBvcERudGI3VkFEWWd2cTB0UGdHc2dUdytKWlcvMGt0dEMyL0sKbWt2a3pNa0NnWUVBL2lrRkxQQjU3ZEJ2NFBYYzBaNEduazRmSnB2a1RjSW9HUTBXOGErclhqOHdYV2ZHMm9DNgpnSnJTVXMrRUFqYzBzT1JwWDArNlQyMWVMQTdKSHVBOCs4Q2FvMHlpc1FPMVBtcERiT0NkeDRvcGg4akZlMnAyCnl5cDZBai9KSFp5dHJ3T0xONC8reEE4YnJBbkh2MWRJaGJSMWszd3cwQ2ZhUnhrdUxTWmpLRmtDZ1lFQSt5MFYKTldPbWNYMmtVdjhCaGtwVllINkIzaHFPMkZINWxic2lLZTJnSjlRRmt4c0ZoQTRlUjhnUTZYdkxJekZuYXFIVApidkJrS1k2V1IxRm9sZ2dhV3N5cjNtazI4TFF0dzJ6blR5QzJtL3N5OVFJSUxOUU83QmZEc2kwc3AzeEx3Y1ROCmEyakFFK2hsZ0dZVncxT3BOTWNUSTBtZzl5dWl4N3ZTZmMrQzBHVUNnWUJQWjR0cFpkd0NFM3ZRb1orU2tiZHAKbitpVmpHREFkbWRHcEZORndPZGVNNG10dE8xb2VJMUwvcEsxTW9ZQWx6VE1DeUJzbWFFUWpZKzlYZ1V4czBiNgpORXRidDJhZ3ZSTFQ1Q2thaS9aZlQrZjN0eDhUbHNoMFl0bnBkL29pV1QvZUROSmkwb2I2dyttV1R4dnJ5SjRzCnY1dDRMM1drb3I3TU5hNjZobUsyU1FLQmdEN3dUdzR2eURkTUNtOFpveUlwWWpkcHU5VVJ4cFdDQlE1MTg5dVoKeGJYMU5PaGxydjRtSTRSTko1KzUrMjc0SkRmZUVRTU5qYXUwSlFmOTZEMGdEcXFOK3NzaWhqZk9qbUVYMnVaRApCajhUdFBNYjdUeCticmJPUmFWU0dJeG5ZdnhNK2tSZDNUT2YyajlRVlVlNm9QMnVuS2NNL2g2eGVucWVIK0tTCnF1N1pBb0dBZnpMTWxGdXlQSnlMaFVCMVpHT0VaaklYNGNhZkR5SWFuaGwxQTVxbW5acTcwaWVzS2FqU1U0RGcKTFRPc21RdXJYZ25uZ0N0ckpyZjI0dEhkYnRkSHFUYVBNeDNGZ0tRU1ZES0pIaWt3cUZ6ZkNsYXpON0tvZHNhVQptRGdYQVVBdmhDbmE5TFoyZm9aUFM0SSt4bHlPZXFzR2t0bHAwUUY0Z2U2eUE4KzF0YUU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-kong-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: kong/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-kong-kong-validations
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRQVNYMk8xMnFGSkRZemNpY1RJVnRDVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5ESXlNRGhhRncwegpOakEwTURreE5ESXlNRGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxNkZNZzN5QlJCL0FYbDVRWDVYeWRBN2dvdzIKN05uMjBzdDdDaWlqeFZObGl4U2VxZFNjQzh3dzVHb2p5TGhPVDEra014ZlBGa2tSWXRwVnY1ZFVlMXZpOW1FNQpEcDRrK0dBTUFMOWJJSGk2WU1XNVRpR3U1d0syN3gwbEdMV1ovMjV6TzBEUDBpbGkwZmhxM2lONC9WdzZTWXdkClRxM1l1VGlCUEhOUmNIZGdac2d6Wk90Sk5acWNTUWNTc21pci9DTDhEendKMzdyN3pVZUtBZGN4aU53K0s5dFgKakF4ZUUyalZySnpmTW5NVjRXdkxkcGVJUXk4YVRScFZoUW1NcGwxKyt0b3ZwQkI5VVBJSnJIQTlJR3hvdTY3TgpvQkRLOWh1MlhHcHd2ZGIyd2VRR2I1dFRRejJkc1ZwSkRNZVhtbzBBS3ZoYzN2VlpWSmhac0kxTmpRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDKzlHZG9jMHZ5eUFFVldObjlrSThObwpIUXpITUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBMlhheEdTWW5vK25RdEhJeHZ6WmJkR012bEdva2lYRG5pCllqbm5paDQwZUtEanBhbTVGT3RodUtoYmtDQUdQME5QU0w0bG5KWmF4WmxxV1FUbWdSdkYrK0tsUHI3ZFNIVGgKVzVvaVN3TmY0YU9hTGJKa0lFdFpCMEl0ZDhoOVpUQjhRK3ljays5U1h6ODMyZSt0NHRVOGJ0ZG5DV2U4dUtiLwoxbmw5bUJHa2Z6d3pMTzUzSjZmTXd1R3kwZjdUeisrSTJoYWkzL1BjUzN4K2ZGdWw0UUdKUVF6UG13ems2bXFhCkc1Wnc4OWJVc1l4MUQvV2NBQlRuZHdSbkpjQTEwOHgxYnB2TExoRzhTbitxRFdvWkJRdGJ1SmE0cndGNGF0Vm0KaVJpa1Q1TWp1RmRnY29TanJQbll5d3EvRUpQSzlERXlXaE9Rc1hVbm8vUlRqZmVCSmxDcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRQVNYMk8xMnFGSkRZemNpY1RJVnRDVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5ESXlNRGhhRncwegpOakEwTURreE5ESXlNRGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxNkZNZzN5QlJCL0FYbDVRWDVYeWRBN2dvdzIKN05uMjBzdDdDaWlqeFZObGl4U2VxZFNjQzh3dzVHb2p5TGhPVDEra014ZlBGa2tSWXRwVnY1ZFVlMXZpOW1FNQpEcDRrK0dBTUFMOWJJSGk2WU1XNVRpR3U1d0syN3gwbEdMV1ovMjV6TzBEUDBpbGkwZmhxM2lONC9WdzZTWXdkClRxM1l1VGlCUEhOUmNIZGdac2d6Wk90Sk5acWNTUWNTc21pci9DTDhEendKMzdyN3pVZUtBZGN4aU53K0s5dFgKakF4ZUUyalZySnpmTW5NVjRXdkxkcGVJUXk4YVRScFZoUW1NcGwxKyt0b3ZwQkI5VVBJSnJIQTlJR3hvdTY3TgpvQkRLOWh1MlhHcHd2ZGIyd2VRR2I1dFRRejJkc1ZwSkRNZVhtbzBBS3ZoYzN2VlpWSmhac0kxTmpRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDKzlHZG9jMHZ5eUFFVldObjlrSThObwpIUXpITUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBMlhheEdTWW5vK25RdEhJeHZ6WmJkR012bEdva2lYRG5pCllqbm5paDQwZUtEanBhbTVGT3RodUtoYmtDQUdQME5QU0w0bG5KWmF4WmxxV1FUbWdSdkYrK0tsUHI3ZFNIVGgKVzVvaVN3TmY0YU9hTGJKa0lFdFpCMEl0ZDhoOVpUQjhRK3ljays5U1h6ODMyZSt0NHRVOGJ0ZG5DV2U4dUtiLwoxbmw5bUJHa2Z6d3pMTzUzSjZmTXd1R3kwZjdUeisrSTJoYWkzL1BjUzN4K2ZGdWw0UUdKUVF6UG13ems2bXFhCkc1Wnc4OWJVc1l4MUQvV2NBQlRuZHdSbkpjQTEwOHgxYnB2TExoRzhTbitxRFdvWkJRdGJ1SmE0cndGNGF0Vm0KaVJpa1Q1TWp1RmRnY29TanJQbll5d3EvRUpQSzlERXlXaE9Rc1hVbm8vUlRqZmVCSmxDcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRQVNYMk8xMnFGSkRZemNpY1RJVnRDVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5ESXlNRGhhRncwegpOakEwTURreE5ESXlNRGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXcxNkZNZzN5QlJCL0FYbDVRWDVYeWRBN2dvdzIKN05uMjBzdDdDaWlqeFZObGl4U2VxZFNjQzh3dzVHb2p5TGhPVDEra014ZlBGa2tSWXRwVnY1ZFVlMXZpOW1FNQpEcDRrK0dBTUFMOWJJSGk2WU1XNVRpR3U1d0syN3gwbEdMV1ovMjV6TzBEUDBpbGkwZmhxM2lONC9WdzZTWXdkClRxM1l1VGlCUEhOUmNIZGdac2d6Wk90Sk5acWNTUWNTc21pci9DTDhEendKMzdyN3pVZUtBZGN4aU53K0s5dFgKakF4ZUUyalZySnpmTW5NVjRXdkxkcGVJUXk4YVRScFZoUW1NcGwxKyt0b3ZwQkI5VVBJSnJIQTlJR3hvdTY3TgpvQkRLOWh1MlhHcHd2ZGIyd2VRR2I1dFRRejJkc1ZwSkRNZVhtbzBBS3ZoYzN2VlpWSmhac0kxTmpRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZDKzlHZG9jMHZ5eUFFVldObjlrSThObwpIUXpITUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBMlhheEdTWW5vK25RdEhJeHZ6WmJkR012bEdva2lYRG5pCllqbm5paDQwZUtEanBhbTVGT3RodUtoYmtDQUdQME5QU0w0bG5KWmF4WmxxV1FUbWdSdkYrK0tsUHI3ZFNIVGgKVzVvaVN3TmY0YU9hTGJKa0lFdFpCMEl0ZDhoOVpUQjhRK3ljays5U1h6ODMyZSt0NHRVOGJ0ZG5DV2U4dUtiLwoxbmw5bUJHa2Z6d3pMTzUzSjZmTXd1R3kwZjdUeisrSTJoYWkzL1BjUzN4K2ZGdWw0UUdKUVF6UG13ems2bXFhCkc1Wnc4OWJVc1l4MUQvV2NBQlRuZHdSbkpjQTEwOHgxYnB2TExoRzhTbitxRFdvWkJRdGJ1SmE0cndGNGF0Vm0KaVJpa1Q1TWp1RmRnY29TanJQbll5d3EvRUpQSzlERXlXaE9Rc1hVbm8vUlRqZmVCSmxDcQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
