---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRRmJpWWw2R3R6OU9nV3lXOExXN2FrREFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5UTXdNekphRncwegpOakEwTURreE5UTXdNekphTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNQWGNiMkZvRUs4SVg0WTZtUTFoRzNJNjNzQzMKNkM2ME04clJobEd3QkIxRE9abGI4Rm9oVnJGZ1ptcnFGZUxCVU1yblVxem1iVlpQWnErZGhHRy9vblFBb09mYwpyTHJVcGd5RndQeEZtaVY0bUR6NFMvR1V3eEFaUSsydXY5Qy9OTDY4N1BlMGVDSERmYjMrZXd2cXcxclpSRlU4CmlQa0Z4K0wzZHhPRkx4RW9ISVhDeHhkZVYzdGR6RFhldk16VzdkUWgxZzhITXBMd0EzL0dkUDNMSFRpTG9rb0kKUC9QeTlFQ05yVlo3eFlxeDdEUGZMelIvUi80a3c4RXRGdTkrYlBhR1hRZjZGNjgrTzg3WHVLTmw1REIzV2wzeApCbzdMZnJJd2FlTTVUMVZVbFNDajRWRlNsU2QwVDNrRTk3Y1hHb0hEVzE2V05HbUN0RTlwVnh3VTl3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKWlE0VHpjT0hDZG8yTitoUGcvekJVZApPelF5TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNWxSWTZmN0ZNTmF0ejBDSWx2SEJKd1F1elhVcGdiY2dwCjJtMDZvdjRRV3NTN0VJYUx0UEtNUU8rU1k4ZkJGc2tFMEpWczROQVE0VndqTDc4TDNrRGs4RzNRY2ErYUFBM0UKWU81Y29reko5bXo0Rlh5SEFHYlY5dU9CUFkvNDdYRjA2NFc1Z0dmNHhFUDQ0RjZMOGd4TUhtVjBHVnk0Szk1UQpieHJxSFJndmlYek1wYnNWWUlTL3N4NUxtWWplNEU0WFRxZ2FOOXRzSmxFc1g0MENzYnR1ejduSUYzTzlXZ04vCk5lbFNIREpMWmtxelcxcmlneVhMVTgya3RPbGl6alZRNFdmaXZYNjdobUVtSndhODRkMjZyYkZkeEhHYlB2cWEKU1ZhSWVsUnpJR1NCT1ZvOVJmbnd4T01oUUpvQk9JZjJRZzRjd21BcmV6aXpZMVptK0xxMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBM1BYY2IyRm9FSzhJWDRZNm1RMWhHM0k2M3NDMzZDNjBNOHJSaGxHd0JCMURPWmxiCjhGb2hWckZnWm1ycUZlTEJVTXJuVXF6bWJWWlBacStkaEdHL29uUUFvT2ZjckxyVXBneUZ3UHhGbWlWNG1EejQKUy9HVXd4QVpRKzJ1djlDL05MNjg3UGUwZUNIRGZiMytld3ZxdzFyWlJGVThpUGtGeCtMM2R4T0ZMeEVvSElYQwp4eGRlVjN0ZHpEWGV2TXpXN2RRaDFnOEhNcEx3QTMvR2RQM0xIVGlMb2tvSVAvUHk5RUNOclZaN3hZcXg3RFBmCkx6Ui9SLzRrdzhFdEZ1OStiUGFHWFFmNkY2OCtPODdYdUtObDVEQjNXbDN4Qm83TGZySXdhZU01VDFWVWxTQ2oKNFZGU2xTZDBUM2tFOTdjWEdvSERXMTZXTkdtQ3RFOXBWeHdVOXdJREFRQUJBb0lCQUJQS2Vib0lNWGY5RlhUbwo0dXEraGdvZFN5U1VnbVJyZW55QkdBODkxZFFvZ3RMdjU0bzVxRzdKYUdjRUFIK0JWZXRVb1MrSWlRTVdEZnFXCmxEYzlRaHJjNVFtRWV3R0ZvbkpWQU0zdVNwV3A4WWxCUE1RZ21VQjNlcXZZNkNRS0lIWXE5MlVLTXNIbjFFaTQKOGNnM293bG9ZN2w1SVBqcnhSYklQMzRNNDRyNWhieDRNdGxwUUd1RUI1em1wNGNWdHptZkRIZGJ1cWdjVlZzQQpEYUxFYTlKWWdZVXBuTjdMaUJqN0dtb3puc3FMTGI3OXE3aEdPbldMdEExWDU2SWNxcFh0Mlk3T3k5VUZScTU2CnZpL0tmR0wzSzhQR3Y3L3J3QlpldWxNUG9oYXhROXovcHQyejNOdnVPUW1IVldPbTJDWGRubEFqOG0xdUtvVksKS0NGT2pPRUNnWUVBL1BjOWpIK3JzOGlpUWh2UGg4b1FkcFZKSW1JTXJ5aDFIQVdxNm5yRktidUJ2eHoxQWkrNQo2ME5RQmErZnJ1M1dObm92MzFEZkhaZ2hZQWdhTDNUbnQwUUVZVVBzb0c3dzc3aWlQOXVLVE5NWnJ6dHVsSWNtClNaenlURTNITGt1amFYekZFdXBvL3hHSEg1K0ljWDB0Y3ZwVUVkYlpvb3l2UXhMci9MTEl1eThDZ1lFQTM1eFkKTkIyTWpvYWhKaDJCR1RTZlVVa0JXeHRody9FS1VEbjBPMTBoT3BsdmRNbnRackJaMDl1MnVvWUsxd3BpQ3k2SAp3MEF6UHM2N2QzNnZhS2V2MDV0ZEdsZElFVnZ3VEc0QkNqQ2c1WXF5aDh2SjlwZUE3Zkl5L3M4dU9QZUREaVc1ClZrcWNKK2xlV1E4cjJRb3ZITGx3bGZjMDJ5d3hrbTNQV0VGTU1Ma0NnWUIrdVdEbEJJUkFvVTdmclV6dXFvUksKMDRoNnFBSFFzWVRSVCttS1k0eG4xcDR0M2xURERxT2x2dWZVb1dGdVlZbEJhejZXTWM1RDVoVTZKWFR3dHpEcApkekoyZzIrRUEyL0J0NDNZVGFQZnpwVDhXdHFQbjVESHFjOGIrSTdDbTNPMmdhRzhVeC9jUDZ5Z1krd1habTBoClAxUmtSMnhwYU83WHZCL3FUS29RVXdLQmdDTjFEeWQwYUExUm04d0hjYWtsaHYzRXJjcGNsU3dVMUtYVUNyNC8KRGozVWhxL21OUmJMYi9NQUxBRjNyOUJaZlNKNHhsNVhsOGlsejJRclduVWw0ZU9VQnpkZUQ3ZHc5TEdwMzlCVgoxYTJRU0s3dnlaNm9kM0ZEcm9KcEo5TXdyRDlhREFGNjR6Z1E4VHorQXQzdmwzamVqdE80MTFESnVUS1c1d0gvCm1LMUJBb0dBSHJTdHVlcDYwZG5qcTZmR2pEQ2lkSXhuTjBXa3U3RzVVdkdqU2V4SkNEN3RTdm5hMW53VVJqOFUKYW9ocW83T1JXVEU0bE52aUc4aWQ3ZlcxM2NRbXhPVEp2OW1jMlZjKzNVNU9scy9kNlhBa0tzOVBQWlU1VmNFdQpoNnNtU21wTk1LeW9xdnJMYlFqUm1zSElKUlZ6V1FOMnN0bklnOVFOMFR0b0wweERydUE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lSQUxmQ29lUjhvNUtHcDZMYWw5VzZabk13RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUmEyOXVaeTFoWkcxcGMzTnBiMjR0WTJFd0hoY05Nall3TkRFeU1UVXpNRE15V2hjTgpNell3TkRBNU1UVXpNRE15V2pBd01TNHdMQVlEVlFRREV5VnJiMjVuTFd0dmJtY3RkbUZzYVdSaGRHbHZiaTEzClpXSm9iMjlyTG10dmJtY3VjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKcFJ0ME1PVGNDUWZRRnpNS0dKdVNwT2syKzJyWER3RzV1Vnk4ZUFJL2xOelloMHRiWUdhUjhTRGMwRGxoNTlmOApxRzhHSUtwdHRzSzBDbUEvcUNlWlErVTRWbzFSbzMzeko1enB4dEErNXhycldLTndEdlJ1bG1zS1paYnB5YmYzCitlVXMvWXlFTkNaUFN1UnRjS3pCZWI3U1dvWlloMUNTNisybk1ETVRiQ0YveGdybTRaZzNveEt3bG1kM2FGeEwKVElsYlZOZ25FWjJTZnlVUkJqdDErWnkxRGlneDY2OWpYYVorWi9XaHN2MmNud3QwZnNFaDlVd2ZhQ2xoUkIrNgozQllCK2RJampUOVRNWkdZeVNWUzlSTWdQVkxuOW9JdEZzY2ZvZGFVbFlHeWlibmo2SjU2M1pvUmlBRmtuN1FSCjZUa0NJcHp4VUdpQlZRbjhTQWZGNndJREFRQUJvNEdUTUlHUU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlYKSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRQpHREFXZ0JTV1VPRTgzRGh3bmFOamZvVDRQOHdWSFRzME1qQXdCZ05WSFJFRUtUQW5naVZyYjI1bkxXdHZibWN0CmRtRnNhV1JoZEdsdmJpMTNaV0pvYjI5ckxtdHZibWN1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnkKdUFSY01scmh3akhZMVFYL3BzRFpuTkVPSG91cTMvYnpqOUlpY1JKTzYvU1JpVlVMQW00alFOK2ZUeW9lOFIwYwo1T3VRVTd6ZDJhUHYyUUNRTFZBTGozQTQrN1ZTbVVzOTIzdDExMHJYNjBPa01yby9nODBkZUJMZ0lQeUdtZWYrCmNnRnh2T0ZMMUVrbjIwaDJ5Tmdzb1RTVlB5SzZNMUcxUWt2cGpsSjE2Rk1vRzhFK0IyZ0ZMVjcyd0R5T2tiQ20KOG9wbm1EUmdXdThIYXZSRi9IN3Juczl1dEhVdk5yVGlXYW52ZkYrTitOZlVnUS9UUUNKRmw3NjllcUxreTd3RwpvVzd4VytrTlhkdTd2QnJ6V2JHWkxOQ0prUUcvQ1Y0ekFhVFhIL3NaeG5FSFpUdDJVK2w3a0gvQTRmWWdFL3dyCkJtaW9GSS9pWnBwbWk3OHB1QnRoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcFJ0ME1PVGNDUWZRRnpNS0dKdVNwT2syKzJyWER3RzV1Vnk4ZUFJL2xOelloMHRiCllHYVI4U0RjMERsaDU5ZjhxRzhHSUtwdHRzSzBDbUEvcUNlWlErVTRWbzFSbzMzeko1enB4dEErNXhycldLTncKRHZSdWxtc0taWmJweWJmMytlVXMvWXlFTkNaUFN1UnRjS3pCZWI3U1dvWlloMUNTNisybk1ETVRiQ0YveGdybQo0Wmczb3hLd2xtZDNhRnhMVElsYlZOZ25FWjJTZnlVUkJqdDErWnkxRGlneDY2OWpYYVorWi9XaHN2MmNud3QwCmZzRWg5VXdmYUNsaFJCKzYzQllCK2RJampUOVRNWkdZeVNWUzlSTWdQVkxuOW9JdEZzY2ZvZGFVbFlHeWlibmoKNko1NjNab1JpQUZrbjdRUjZUa0NJcHp4VUdpQlZRbjhTQWZGNndJREFRQUJBb0lCQUFKaXdpd09zb3RDM0tQcApMZVVySWxSVnRtQ3RxNHZnOTRFUk1Qdis5RkkvV3JXaHhpRS9laTVreml3SUdEMFVadWM4SzNkL1h2UjhIY1BrCm5pYmM0NThTaWR6ZVQrYXY1RHFYVHQxN2x0MGFDM3FOYWdvZFNCZk9WaWtmcENNeEVGbEJFWVJjYW5DaWVSVFkKOWlmaHB5NE9MdFgyQ1FOemk1dnpKQzVUSHAyNlhEKzA3SW1wb1N2bVBXbVFqeWJzYklUSytRYUt4WE1NOWMvbgpXVkVMRElDN0JVRk5QTW1Uakt6Njh6SUo2dHRldWVhV3ZyQU4vU1FhMUIxeTBsRDRnQ3FRYkJaOXJLNzlxMDBHClJoVWRGQzI1M3hacXVwd0FJelJoSENxQmExdTRyaUp5eGRCdmVlMXppcEhiQkV0aGRFOFBlWjE4clFaM3RYRDUKOVRhRWRpa0NnWUVBeUNhRTN0UlJXTmpoMU00d0R1SkJzVVRrcmR4b1FVRnZwZ1orWksvbzhhYWRWOWd0UkJpRApUY1VBSnpGUE9zU3hPQ3ZuTXdPOUJNQUdMcmJmKzdYNGJJUTl0U0R5V3UvWi9COUFjbFZRS3JzYWhVTGEwNG56ClVxeHVpZ0oyaStLeDF0emIyT3NTYVo5V2hhbVlqVTZjdWorZktYWHNldExqeEZjRkhtNDhnRVVDZ1lFQTB5MnIKUlVIeUNFYjRpOUZxVG5FaURTRjJPdnVaelAzQkJOWnBQOVIzWjNWMU94QUFUN3ZWUGJ0YVZNaVlwTUlUMGg0VgpsVllSazl0RExYRDNSK0FjdWVwNVBURVFxbTI1RUE3cThBTVFBbTd4Rml0eXFvZGppNXhGZzUxVEdGYmo1cmxUCjFhMytEQ0JtcnVkeExrRTFzL210SUplR2JITU1NbVpCNk01Q0NHOENnWUVBcjJ0TEl2MVUrcGpEZlQ3bFVmWXQKZTArVldXZ0dtOExkTnRjVUtlMGZMY1JJdlBnRDNGM2JudXFkVXJ4ZDQzVUdtZU9vczhhQUFNekgzbU43ZGVJcwpBL2YzR1d2eDNZL0FMcis1UFR2V2trMEFWbkdjMXJCZWFVUWxjYUh0QW5kQ1JMMjNsYXVacktieEx4N1FUSERzCjNqUHFyR3psUVZUYU9YZkhUYjl5R1QwQ2dZRUFvdWlmTUUxZ0ppeUJ2bkt0bkplLzJmdFBWczhUWmNUM3F3Q3cKcnRIN3p1OFlvWmlGZFAwRTBwdCtZdHRnamZFK0V5Q3NLOGo2eEdJb1g1eSsxazY0T2wvOGFVMDVleEFyN0l4bApod1FGektyREJ3UTdiL3dEdWdheXhZYVBQTDZERDFFMnNDZUtUTmFPQUMyQTdWcld6K0V6UW1wQ0E5VjR1a1NTClljTUR3N2NDZ1lCUVN6OGlPN3RWeFFIc3dMU0o2OGxQVDN2c0xqbFo2R1pQUUtJdFVtMzR6SEIzTDUzYVZ3a2oKSzkvWnlYUm1oTExKeGRaS1QvampYazZqejJkUFd1M0JQYk9vbDZYUFdzOWJvQjBJeXdXd25sbGhaN3VaTURvMApDK2lyVnVLWEtwSHBpbnE1TlZGd0lXTXdPZDBlQzVJZUxGUnpDay96MTU5bkpMaW43cDFMQmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-kong-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: kong/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-kong-kong-validations
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRRmJpWWw2R3R6OU9nV3lXOExXN2FrREFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5UTXdNekphRncwegpOakEwTURreE5UTXdNekphTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNQWGNiMkZvRUs4SVg0WTZtUTFoRzNJNjNzQzMKNkM2ME04clJobEd3QkIxRE9abGI4Rm9oVnJGZ1ptcnFGZUxCVU1yblVxem1iVlpQWnErZGhHRy9vblFBb09mYwpyTHJVcGd5RndQeEZtaVY0bUR6NFMvR1V3eEFaUSsydXY5Qy9OTDY4N1BlMGVDSERmYjMrZXd2cXcxclpSRlU4CmlQa0Z4K0wzZHhPRkx4RW9ISVhDeHhkZVYzdGR6RFhldk16VzdkUWgxZzhITXBMd0EzL0dkUDNMSFRpTG9rb0kKUC9QeTlFQ05yVlo3eFlxeDdEUGZMelIvUi80a3c4RXRGdTkrYlBhR1hRZjZGNjgrTzg3WHVLTmw1REIzV2wzeApCbzdMZnJJd2FlTTVUMVZVbFNDajRWRlNsU2QwVDNrRTk3Y1hHb0hEVzE2V05HbUN0RTlwVnh3VTl3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKWlE0VHpjT0hDZG8yTitoUGcvekJVZApPelF5TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNWxSWTZmN0ZNTmF0ejBDSWx2SEJKd1F1elhVcGdiY2dwCjJtMDZvdjRRV3NTN0VJYUx0UEtNUU8rU1k4ZkJGc2tFMEpWczROQVE0VndqTDc4TDNrRGs4RzNRY2ErYUFBM0UKWU81Y29reko5bXo0Rlh5SEFHYlY5dU9CUFkvNDdYRjA2NFc1Z0dmNHhFUDQ0RjZMOGd4TUhtVjBHVnk0Szk1UQpieHJxSFJndmlYek1wYnNWWUlTL3N4NUxtWWplNEU0WFRxZ2FOOXRzSmxFc1g0MENzYnR1ejduSUYzTzlXZ04vCk5lbFNIREpMWmtxelcxcmlneVhMVTgya3RPbGl6alZRNFdmaXZYNjdobUVtSndhODRkMjZyYkZkeEhHYlB2cWEKU1ZhSWVsUnpJR1NCT1ZvOVJmbnd4T01oUUpvQk9JZjJRZzRjd21BcmV6aXpZMVptK0xxMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRRmJpWWw2R3R6OU9nV3lXOExXN2FrREFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5UTXdNekphRncwegpOakEwTURreE5UTXdNekphTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNQWGNiMkZvRUs4SVg0WTZtUTFoRzNJNjNzQzMKNkM2ME04clJobEd3QkIxRE9abGI4Rm9oVnJGZ1ptcnFGZUxCVU1yblVxem1iVlpQWnErZGhHRy9vblFBb09mYwpyTHJVcGd5RndQeEZtaVY0bUR6NFMvR1V3eEFaUSsydXY5Qy9OTDY4N1BlMGVDSERmYjMrZXd2cXcxclpSRlU4CmlQa0Z4K0wzZHhPRkx4RW9ISVhDeHhkZVYzdGR6RFhldk16VzdkUWgxZzhITXBMd0EzL0dkUDNMSFRpTG9rb0kKUC9QeTlFQ05yVlo3eFlxeDdEUGZMelIvUi80a3c4RXRGdTkrYlBhR1hRZjZGNjgrTzg3WHVLTmw1REIzV2wzeApCbzdMZnJJd2FlTTVUMVZVbFNDajRWRlNsU2QwVDNrRTk3Y1hHb0hEVzE2V05HbUN0RTlwVnh3VTl3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKWlE0VHpjT0hDZG8yTitoUGcvekJVZApPelF5TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNWxSWTZmN0ZNTmF0ejBDSWx2SEJKd1F1elhVcGdiY2dwCjJtMDZvdjRRV3NTN0VJYUx0UEtNUU8rU1k4ZkJGc2tFMEpWczROQVE0VndqTDc4TDNrRGs4RzNRY2ErYUFBM0UKWU81Y29reko5bXo0Rlh5SEFHYlY5dU9CUFkvNDdYRjA2NFc1Z0dmNHhFUDQ0RjZMOGd4TUhtVjBHVnk0Szk1UQpieHJxSFJndmlYek1wYnNWWUlTL3N4NUxtWWplNEU0WFRxZ2FOOXRzSmxFc1g0MENzYnR1ejduSUYzTzlXZ04vCk5lbFNIREpMWmtxelcxcmlneVhMVTgya3RPbGl6alZRNFdmaXZYNjdobUVtSndhODRkMjZyYkZkeEhHYlB2cWEKU1ZhSWVsUnpJR1NCT1ZvOVJmbnd4T01oUUpvQk9JZjJRZzRjd21BcmV6aXpZMVptK0xxMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRRmJpWWw2R3R6OU9nV3lXOExXN2FrREFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRJeE5UTXdNekphRncwegpOakEwTURreE5UTXdNekphTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNQWGNiMkZvRUs4SVg0WTZtUTFoRzNJNjNzQzMKNkM2ME04clJobEd3QkIxRE9abGI4Rm9oVnJGZ1ptcnFGZUxCVU1yblVxem1iVlpQWnErZGhHRy9vblFBb09mYwpyTHJVcGd5RndQeEZtaVY0bUR6NFMvR1V3eEFaUSsydXY5Qy9OTDY4N1BlMGVDSERmYjMrZXd2cXcxclpSRlU4CmlQa0Z4K0wzZHhPRkx4RW9ISVhDeHhkZVYzdGR6RFhldk16VzdkUWgxZzhITXBMd0EzL0dkUDNMSFRpTG9rb0kKUC9QeTlFQ05yVlo3eFlxeDdEUGZMelIvUi80a3c4RXRGdTkrYlBhR1hRZjZGNjgrTzg3WHVLTmw1REIzV2wzeApCbzdMZnJJd2FlTTVUMVZVbFNDajRWRlNsU2QwVDNrRTk3Y1hHb0hEVzE2V05HbUN0RTlwVnh3VTl3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKWlE0VHpjT0hDZG8yTitoUGcvekJVZApPelF5TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNWxSWTZmN0ZNTmF0ejBDSWx2SEJKd1F1elhVcGdiY2dwCjJtMDZvdjRRV3NTN0VJYUx0UEtNUU8rU1k4ZkJGc2tFMEpWczROQVE0VndqTDc4TDNrRGs4RzNRY2ErYUFBM0UKWU81Y29reko5bXo0Rlh5SEFHYlY5dU9CUFkvNDdYRjA2NFc1Z0dmNHhFUDQ0RjZMOGd4TUhtVjBHVnk0Szk1UQpieHJxSFJndmlYek1wYnNWWUlTL3N4NUxtWWplNEU0WFRxZ2FOOXRzSmxFc1g0MENzYnR1ejduSUYzTzlXZ04vCk5lbFNIREpMWmtxelcxcmlneVhMVTgya3RPbGl6alZRNFdmaXZYNjdobUVtSndhODRkMjZyYkZkeEhHYlB2cWEKU1ZhSWVsUnpJR1NCT1ZvOVJmbnd4T01oUUpvQk9JZjJRZzRjd21BcmV6aXpZMVptK0xxMAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
