apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql-ha/templates/pgpool/deployment.yaml
  - postgresql-ha/templates/pgpool/networkpolicy.yaml
  - postgresql-ha/templates/pgpool/pdb.yaml
  - postgresql-ha/templates/pgpool/service.yaml
  - postgresql-ha/templates/postgresql/configmap.yaml
  - postgresql-ha/templates/postgresql/networkpolicy.yaml
  - postgresql-ha/templates/postgresql/pdb.yaml
  - postgresql-ha/templates/postgresql/scripts-configmap.yaml
  - postgresql-ha/templates/postgresql/service-headless.yaml
  - postgresql-ha/templates/postgresql/service.yaml
  - postgresql-ha/templates/postgresql/statefulset.yaml
  - postgresql-ha/templates/postgresql/witness-pdb.yaml
  - postgresql-ha/templates/serviceaccount.yaml
