postgresql:
  password: ""
  repmgrPassword: ""
  image:
    tag: 17.2.0-debian-12-r6
  resources:
    limits:
      cpu: 375m
      memory: 384Mi
    requests:
      cpu: 250m
      memory: 256Mi
pgpool:
  image:
    tag: 4.5.5-debian-12-r3
global:
  postgresql:
    auth:
      existingSecret: vault-postgres-secret