---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRZmNsdzRnUXhWTWpHSzdCN1hRRGdUVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd056UXhOVGhhRncwegpOakEwTVRRd056UXhOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXF3QzVTSUxGVjdCYyt4SjNjQUI3UzdON2ZnZ2UKeUxSejVsVFJxRDl0OFcrR21yekVDWnhUOHdQZ1orTDVNRHJKZFMweHk4VVVJRnpQQzRtVjFHVEE4L3FxNnRqKwpQVWZKMGtKQUZDWVlXSXE4WDhkRjV2eUdXdldKVi9MdXRBWjVRVnBtMnlXcnJiRTl1citPMjNIYTZyTXJqS0FCCldVa1FwSERHWk5YaHdVSnZPVHNHdWNua2dWZ0NVb3NpaEhSSmJ3Q0tUSnU3Z3dqZzBlTTJSbDBnMEFmMjhDT0MKbXBmK1c4UCtPcTIyUTE0WnI3TklORi93bXYvTDNGWWFpRTNxTWdlQ2RIaVF2N3FodGUyOVFNWEliOHhyeHl2UwpQRkpUT3AzYmY4OUhQQjlsMnlSenQwcG1GRytUWnp4OHI4VEdkeXdRMWQzZzdSMlJBY3BjZnJFS1hRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJKytxbDVXcHR1clQzUE1NZzJTNEhVbwpVTVUwTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCL1EzRmdNRjhTL2FRL2VxUHZBQU9xUHZDMmhzMkhrQlQ3CnVWOGN5VWROZUpFbnphbW12MUdUR2NoMk5kRTYySlVhdmpkZ3g4MWZ6VmN0cjAzVTVqcHU3M3Y3cEhxbGVsUVQKS3RJUmp4TVJMSGIwWC9HazZURUN2VFNiWnAwZit4TEdYa0RSbS9rZW80Y0VWSkRnNUkrZmVIV1ByenIvR2tpMQp2ekF6MVJ1Z0lvZnh0MmdPemJRN3FIUXFuZFhSQzU0S1gzZWNYSDkxeXhyK0VnYXhVcVh6THIwTXRXbUo5aWl6Cmd0bDhWaXE1QWhuc0p2WXdKZjB2NElyUENWcUk0a2lhNFNGcS92M3BwM2tjbm9qbzIzaEZqcThzdkNmMVBBZzgKdGVXb3RlbFFWSDRoM2dwakhDM0RCTjF5WlplYTY5d3djSjM1TFl2SWl4MGhISm9UakNWbgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcXdDNVNJTEZWN0JjK3hKM2NBQjdTN043ZmdnZXlMUno1bFRScUQ5dDhXK0dtcnpFCkNaeFQ4d1BnWitMNU1EckpkUzB4eThVVUlGelBDNG1WMUdUQTgvcXE2dGorUFVmSjBrSkFGQ1lZV0lxOFg4ZEYKNXZ5R1d2V0pWL0x1dEFaNVFWcG0yeVdycmJFOXVyK08yM0hhNnJNcmpLQUJXVWtRcEhER1pOWGh3VUp2T1RzRwp1Y25rZ1ZnQ1Vvc2loSFJKYndDS1RKdTdnd2pnMGVNMlJsMGcwQWYyOENPQ21wZitXOFArT3EyMlExNFpyN05JCk5GL3dtdi9MM0ZZYWlFM3FNZ2VDZEhpUXY3cWh0ZTI5UU1YSWI4eHJ4eXZTUEZKVE9wM2JmODlIUEI5bDJ5UnoKdDBwbUZHK1Raeng4cjhUR2R5d1ExZDNnN1IyUkFjcGNmckVLWFFJREFRQUJBb0lCQUJkWHAvTWY5clE3bk5XZwo5YkRTUUFKYlk3WVdnYTFBQkxvaVJlUkRsRXhxdnVNTWRXNGlhc3MzY2tCOEdTdmVPblhHVDQvVFBTWVZ4U1Y4CkNIblBydzhlM29ua1NRQXdkbm8vRk9Rck54T1BESnUrWmVwYitqTWNaVDBlS2p0a3p0Uis5SjloaXdmUXMrNTAKQzVvazlvOG5HZ0MrTHJEemFsUW9HTXpXN1ZRbDlrcUFYTU0wMHZxM3NLNmtjdTVJOFVoUHVpanYxNVpOSlFsZQptWUFJcTZUdUh6bXBCZHRFZmhaSlJ4VTcwdnpnZHFNUS8vczdCelc5VGVwS0l3Q212RytmMDNNcldGMVpJYnN3CnRKV21Xc2VRTjB6OEdrRXJWOTlvZitCVWFvVUpLWVp4b2ZFT3pJRkdOUVo5ZDladkxtTGl5V3dka2JRQXRZOXcKU2xJL2tqa0NnWUVBMVp4a2xZRzJPeVhiRzN0ckdGWjluT1Mxc2x5NXlYWmtGQjVSRnhTZytGc3JERStXaGw2RwpTNlRIZFBxaitvYjRaQmVna3FoWWNiRjk3dUVKM2FPSFJzY3lpVEJIOVE3YnBJTVdNWEUzS0N2Rlh3N3VJVjN5ClR1NDU2ZC9HeFR4WjNWNXpGWi9xRWVLVmxvdGJZUU94cG5qdS9TeUhNTU9BSUlLYnNoTk45ak1DZ1lFQXpPL08KUjNPcTNTcHJzU1dkai9lMkE0Mzd5cy9WSEVoZmtVZVZlVUoveVlVQ1Y0dmgvVE1FTmJKN3VXelRMMFNSa0MxMQpzT2VTY1hES0tFK1pkdWVXZVpINHAra3E5SndxMlNJUGQvRGxqTEhUNnFIU3NEUGtRREwzOTQyMTViYWpTczFNCnpLVHlvSXBlbGh0a25sWVZLVzg5SUE0WXAwM0dKT09EeHVmZXpTOENnWUFzaEUxS0F5QlJMMUI4WjdvbjlrNXoKVmc2dnZ6ZFF6d1dJVTlFZWVFUWJ2aFE0bXBXS0owVGhtdE9lZzJXTkhuZkJsRkw0ZlhFQk1MWklCRW9rRUtKdQprN0RxZWs5a3VOWDVjUUE5Q1pVdklBQWdFV0o3UGJMejFCM3BxYU1wRTZ5K3Y2SklUVzFna05JUDc3YjVmdVdWCkJmcjRkRUV3WG0zaldKVE9CY3ZubFFLQmdRQ21HaCs1TGZqbzlUNy8vNXJyV3p5OU9ORkNHcDJDSk83QWs2S0UKKys4UzZLbHpSNzlOTjVKTDYzUDRZRW55MzhLVGR5VVMwejZRajNocW44bWs1Q1BFT1JtdkRuOXdienNUYmxYWApRdnJxeEI4YzV6Z2E5SlFscktucWpZTkd3bmNyWTZiQm4xZS80eWF5eDFVUU9IbENjaFM2N0hIeStFaUhFWmgzCkdPd3VwUUtCZ0dBa1cwVCtpZEo0L1FQOGhSclhFRzFhenlRQ3hYVld2d0NQYk5nc3gyMk5HOUp0WHNwQkFhR0sKTzVFQjVOeW5KdlMwcnpLeVpBOEtVcEI5aFUzSW5Lb2NhNUtUSVJicHp6dW9nSUZURGlYdjg1a0Z1TFpjOGZQcwpyRXJYRGV2Skh2SW5CM05VdGVTdW5ha25pRVVBbnQ2MW00ZG5Gd1d3cmljOXBsUi9MSk93Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lRQnVLMzBjanJRZ1Y1cHpoNnBsS1pwVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd056UXhOVGhhRncwegpOakEwTVRRd056UXhOVGhhTURBeExqQXNCZ05WQkFNVEpXdHZibWN0YTI5dVp5MTJZV3hwWkdGMGFXOXVMWGRsClltaHZiMnN1YTI5dVp5NXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzYKd0dhcFFNMGVKN0JiM1NNdGhlb1BnUjBhQmlseTROdUtjbU1YMS9lRldlNXN3MThXUWhvOVRDWEVSeUQzenFmTgpYOTcvaTMrR0VXQ0Z2bkNoU3J3MXpjUkRDMGxWQUdrOGllMDFGOTNoUFphWXhpOEo1R2hja0xOdmdyQi9MRzJZCkxEdG1oK0UrMmIvWnBmUmV3WXdBaEFQWHdkSGR4ampKZlY4THA5TUpNd3MyVUI4aWJ3MUw4dnErVGVmaVBPWUYKenVkY3JNZm9tMTdRUkFqcEVJUXhWclpFOVFpODZBODlBYjhrRFRaMCt3dW85R001YUk5Vi9OQ05PN01lYlFldgpYNjg0anNUN2s1dmxOdXJHc2RQUjlEajdtTEdTM2MyZDUzdEtyRVh5RXY4dnRhQ25HSlpYS25sWjJJZnFRcHZaCkFBV09YcEYwL2ZYMXpKVit0Nm5WQWdNQkFBR2pnWk13Z1pBd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWQpNQmFBRkkrK3FsNVdwdHVyVDNQTU1nMlM0SFVvVU1VME1EQUdBMVVkRVFRcE1DZUNKV3R2Ym1jdGEyOXVaeTEyCllXeHBaR0YwYVc5dUxYZGxZbWh2YjJzdWEyOXVaeTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHY3oKZzBNcTBzUUl6RWx3clJBRk9BSk1wTUFIZDdqajlZNGlxUEJoRTVJcGRudXVPS3dXVDMxV0Y3S1F4ZjQ3cmFhZwpBVnpsSmF1Y05XSS9VUzYvcUlDa0tnaHI2dE9wRmh1endIVEJMZEZ1TytpbmRMNUUzc0tGYUlIVnZydWtKQjBJClRkdCtRMWNIdTR6T2dnSzY2SElZRGdPMlJQTUNEOGJRdldXd1JWSkFyNHExcTgyYTFDbXMwNHlGbjNOeWt1NmIKcGt4dUJjT1hnVjRCODRRbk81c1lrS0gydHlIbmZmUVJ1SnZhdDNtVXBjc2FPQ2xzVUNCamN1YzNsdlRjTThNMwpBajJFREo1cUk4ZEZ4bzhDbitCRHlPNWxTVHNFaE5QTFBlWmlKN1JlVGRVenZVb0wzeDJPS1dLTXY0S2lNSjJhCncwQ2tzRmp1VG10KzJSZGs1ZTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdXNCbXFVRE5IaWV3VzkwakxZWHFENEVkR2dZcGN1RGJpbkpqRjlmM2hWbnViTU5mCkZrSWFQVXdseEVjZzk4Nm56Vi9lLzR0L2hoRmdoYjV3b1VxOE5jM0VRd3RKVlFCcFBJbnROUmZkNFQyV21NWXYKQ2VSb1hKQ3piNEt3Znl4dG1Ddzdab2ZoUHRtLzJhWDBYc0dNQUlRRDE4SFIzY1k0eVgxZkM2ZlRDVE1MTmxBZgpJbThOUy9MNnZrM240anptQmM3blhLekg2SnRlMEVRSTZSQ0VNVmEyUlBVSXZPZ1BQUUcvSkEwMmRQc0xxUFJqCk9XaVBWZnpRalR1ekhtMEhyMSt2T0k3RSs1T2I1VGJxeHJIVDBmUTQrNWl4a3QzTm5lZDdTcXhGOGhML0w3V2cKcHhpV1Z5cDVXZGlINmtLYjJRQUZqbDZSZFAzMTljeVZmcmVwMVFJREFRQUJBb0lCQUEzQ1ZDMy9LTDJpaGZOVwp1UnRIQlFZc2FKVDh4RHdEQmhuT3NLOVdpWldKR1RCcE9vMjh4QXNsRzVrNDlseGJuUEJjTW1WWWhVWSs3SUllCkZGVkYyTlVMK254SURoaVZwYXRBckRuZnJzakVEVjduSnhzTytZTnNZOVFBNkhrT01Hcm9RMTRiLzhQdUxoemUKaGNFZmVHMm5URk11cEFRM2NRS2pXb2ZVenc4YjA3OXNmclBPelhtOEtFRmxEV3lZN0p4b2xmQUhlY0xrWkw5dAp1aDRYbDVIQWh4YjREM3kzM0wxN05sQmM2ZDV4Y0VYUEFwM3VZWUk5SWhxd1Zhd0NRdkl2YzBEaFR6NlNHSXJWClJ4aGlhcFlaM0JvbUVzNjEwS2tadXNJSmJna2FROHNnNmg4SkUwQjdyS0ZXcU0xeCtndWNTTDFEY1BDZVUvQWgKNmZxcUoxRUNnWUVBeE5VMmxGckNpSkgyWFQycEhZWkxKei8remJuWU0yMUw2Q3I1cEFkd1pBSzJoNGF0VzcxNwpGMkV1bk1XbC9WdHJUaWRNRTFXcytLTFE0ZTlmQ3hTbWtxc1pLQ2ZPOEdBQnpHVFpGUU93R1J0ZlVtTndvYW5CCnl3RWFSakZEb3F0dlVRdkZ3UU0wVG4yNm01ZEVKaGVVajBhS1hPU2xGYThIaHkwZEk1aEZjZDBDZ1lFQTh1Tm8KRGsyTG9jZFhKUmc3NEZxWnNtYllwTytvcWs1S0dlWXZ4cnlVdDltVUxxbjNSb1pRRTBjT3FJNEFkZmtFc0EyYwpoUGJZbDg2VEhVOFVZdUpBNFJrSnFtS0FKZ3p1Z2VtZUxVS2ZLMkJ0Njk2SGYzSlFuSWVnWTBPbmtTUlNDWVlDCm9RQmZSTGZhaUpYS1JKcXRjSjBMdkZ0YWhEb0JpWUhqRFhQUUpGa0NnWUEwVkx0K0ZlTkNqQXdFSGpDb09Od2kKUTFGclFNM0tYblNmOVUwSjN6Qnlab1pBNGYyVk5udFRhL01JbTBQV2FFZlBMNE42WUh6c1hkMUxOR2tBZVMwUQpNWTB1citiRTRjR1lwZmRSTHZuU3N3UlUwenRPditOV0phVG1wSkptM1UxckxzWVUydFU5U1JBajdjT2duUVJTClUxN1Y4N1F3WDZpUXQ5M1hhTlNOd1FLQmdCa25TY2hwYVhONGxHTElEck5lVHBwMklpdDZra29JejQyOUUrZU4KOGd6VUlJOXdsS1llRkw3YVZmOUlyVzJLTzEwTUc5QjlTOUwwMXJGclZoNGpkanFaZ0RHLy82dHhIV1lnem51NwpjWVpwZHhpOU0rVVQ3cHMzUkhuak1NQk1OWjY4M1JyVlVnaG96ZDNsUFV3N2hJaXNDdUlYeDlqM3ROOExyM3JlCktva0pBb0dBSlNrRUtMTGZhWFRWUlpCZVZlUVoxc0lkTzg0dko0U3hOWlMzb2FpTG1HWGNtVzRWczVKanYxY2QKeXpLU3VKRVBEZ2QydzdUd0xERy9Qdjd1TFA0V1JITjU3bDNPcDkvb29iVVM4VE5IZWx2VmUyMllCdGJZNjRjTQpBQi8yL2NjZW1EcmJWTTQyRmwzZGRMNDcrUmtqdmdta0p3THdxRUoySG9lTVdDeWNpN3M9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-kong-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: kong/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-kong-kong-validations
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRZmNsdzRnUXhWTWpHSzdCN1hRRGdUVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd056UXhOVGhhRncwegpOakEwTVRRd056UXhOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXF3QzVTSUxGVjdCYyt4SjNjQUI3UzdON2ZnZ2UKeUxSejVsVFJxRDl0OFcrR21yekVDWnhUOHdQZ1orTDVNRHJKZFMweHk4VVVJRnpQQzRtVjFHVEE4L3FxNnRqKwpQVWZKMGtKQUZDWVlXSXE4WDhkRjV2eUdXdldKVi9MdXRBWjVRVnBtMnlXcnJiRTl1citPMjNIYTZyTXJqS0FCCldVa1FwSERHWk5YaHdVSnZPVHNHdWNua2dWZ0NVb3NpaEhSSmJ3Q0tUSnU3Z3dqZzBlTTJSbDBnMEFmMjhDT0MKbXBmK1c4UCtPcTIyUTE0WnI3TklORi93bXYvTDNGWWFpRTNxTWdlQ2RIaVF2N3FodGUyOVFNWEliOHhyeHl2UwpQRkpUT3AzYmY4OUhQQjlsMnlSenQwcG1GRytUWnp4OHI4VEdkeXdRMWQzZzdSMlJBY3BjZnJFS1hRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJKytxbDVXcHR1clQzUE1NZzJTNEhVbwpVTVUwTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCL1EzRmdNRjhTL2FRL2VxUHZBQU9xUHZDMmhzMkhrQlQ3CnVWOGN5VWROZUpFbnphbW12MUdUR2NoMk5kRTYySlVhdmpkZ3g4MWZ6VmN0cjAzVTVqcHU3M3Y3cEhxbGVsUVQKS3RJUmp4TVJMSGIwWC9HazZURUN2VFNiWnAwZit4TEdYa0RSbS9rZW80Y0VWSkRnNUkrZmVIV1ByenIvR2tpMQp2ekF6MVJ1Z0lvZnh0MmdPemJRN3FIUXFuZFhSQzU0S1gzZWNYSDkxeXhyK0VnYXhVcVh6THIwTXRXbUo5aWl6Cmd0bDhWaXE1QWhuc0p2WXdKZjB2NElyUENWcUk0a2lhNFNGcS92M3BwM2tjbm9qbzIzaEZqcThzdkNmMVBBZzgKdGVXb3RlbFFWSDRoM2dwakhDM0RCTjF5WlplYTY5d3djSjM1TFl2SWl4MGhISm9UakNWbgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRZmNsdzRnUXhWTWpHSzdCN1hRRGdUVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd056UXhOVGhhRncwegpOakEwTVRRd056UXhOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXF3QzVTSUxGVjdCYyt4SjNjQUI3UzdON2ZnZ2UKeUxSejVsVFJxRDl0OFcrR21yekVDWnhUOHdQZ1orTDVNRHJKZFMweHk4VVVJRnpQQzRtVjFHVEE4L3FxNnRqKwpQVWZKMGtKQUZDWVlXSXE4WDhkRjV2eUdXdldKVi9MdXRBWjVRVnBtMnlXcnJiRTl1citPMjNIYTZyTXJqS0FCCldVa1FwSERHWk5YaHdVSnZPVHNHdWNua2dWZ0NVb3NpaEhSSmJ3Q0tUSnU3Z3dqZzBlTTJSbDBnMEFmMjhDT0MKbXBmK1c4UCtPcTIyUTE0WnI3TklORi93bXYvTDNGWWFpRTNxTWdlQ2RIaVF2N3FodGUyOVFNWEliOHhyeHl2UwpQRkpUT3AzYmY4OUhQQjlsMnlSenQwcG1GRytUWnp4OHI4VEdkeXdRMWQzZzdSMlJBY3BjZnJFS1hRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJKytxbDVXcHR1clQzUE1NZzJTNEhVbwpVTVUwTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCL1EzRmdNRjhTL2FRL2VxUHZBQU9xUHZDMmhzMkhrQlQ3CnVWOGN5VWROZUpFbnphbW12MUdUR2NoMk5kRTYySlVhdmpkZ3g4MWZ6VmN0cjAzVTVqcHU3M3Y3cEhxbGVsUVQKS3RJUmp4TVJMSGIwWC9HazZURUN2VFNiWnAwZit4TEdYa0RSbS9rZW80Y0VWSkRnNUkrZmVIV1ByenIvR2tpMQp2ekF6MVJ1Z0lvZnh0MmdPemJRN3FIUXFuZFhSQzU0S1gzZWNYSDkxeXhyK0VnYXhVcVh6THIwTXRXbUo5aWl6Cmd0bDhWaXE1QWhuc0p2WXdKZjB2NElyUENWcUk0a2lhNFNGcS92M3BwM2tjbm9qbzIzaEZqcThzdkNmMVBBZzgKdGVXb3RlbFFWSDRoM2dwakhDM0RCTjF5WlplYTY5d3djSjM1TFl2SWl4MGhISm9UakNWbgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRZmNsdzRnUXhWTWpHSzdCN1hRRGdUVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd056UXhOVGhhRncwegpOakEwTVRRd056UXhOVGhhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXF3QzVTSUxGVjdCYyt4SjNjQUI3UzdON2ZnZ2UKeUxSejVsVFJxRDl0OFcrR21yekVDWnhUOHdQZ1orTDVNRHJKZFMweHk4VVVJRnpQQzRtVjFHVEE4L3FxNnRqKwpQVWZKMGtKQUZDWVlXSXE4WDhkRjV2eUdXdldKVi9MdXRBWjVRVnBtMnlXcnJiRTl1citPMjNIYTZyTXJqS0FCCldVa1FwSERHWk5YaHdVSnZPVHNHdWNua2dWZ0NVb3NpaEhSSmJ3Q0tUSnU3Z3dqZzBlTTJSbDBnMEFmMjhDT0MKbXBmK1c4UCtPcTIyUTE0WnI3TklORi93bXYvTDNGWWFpRTNxTWdlQ2RIaVF2N3FodGUyOVFNWEliOHhyeHl2UwpQRkpUT3AzYmY4OUhQQjlsMnlSenQwcG1GRytUWnp4OHI4VEdkeXdRMWQzZzdSMlJBY3BjZnJFS1hRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZJKytxbDVXcHR1clQzUE1NZzJTNEhVbwpVTVUwTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCL1EzRmdNRjhTL2FRL2VxUHZBQU9xUHZDMmhzMkhrQlQ3CnVWOGN5VWROZUpFbnphbW12MUdUR2NoMk5kRTYySlVhdmpkZ3g4MWZ6VmN0cjAzVTVqcHU3M3Y3cEhxbGVsUVQKS3RJUmp4TVJMSGIwWC9HazZURUN2VFNiWnAwZit4TEdYa0RSbS9rZW80Y0VWSkRnNUkrZmVIV1ByenIvR2tpMQp2ekF6MVJ1Z0lvZnh0MmdPemJRN3FIUXFuZFhSQzU0S1gzZWNYSDkxeXhyK0VnYXhVcVh6THIwTXRXbUo5aWl6Cmd0bDhWaXE1QWhuc0p2WXdKZjB2NElyUENWcUk0a2lhNFNGcS92M3BwM2tjbm9qbzIzaEZqcThzdkNmMVBBZzgKdGVXb3RlbFFWSDRoM2dwakhDM0RCTjF5WlplYTY5d3djSjM1TFl2SWl4MGhISm9UakNWbgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
