---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRTHIzUDR1bzFEMDBuNjQ2QmJLNSszakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd09ETXdNVE5hRncwegpOakEwTVRRd09ETXdNVE5hTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVKNjJpYktTWTdxZjhHOEgrOEtsSDJmUWl3MVIKQUN1eTFReFhtNDJqeUZXNzUvNGRwU255TzU2N2RUWk00RVg2Nmh3QStpNUp1UUNWL0hsQi9BRExPM0d2a3FvSApIenBxNG1WdWlQRDdJcHl0cWtGM3VUNCtPckpPZjZTRGNEYjh0dTFDbGgxblF3WGhVSTUwT28zT3RpcHRuZlR0Ck9GZFk1aGN0OGlOQWdIbitPYWNybEZiNzZsSjhjYWQzMis2Zi81QkZEeHV4eXB2TEtRNnIwdm5jNE5RdVpoSWMKZHdMZis5b3l1VnBoRERiTUhsWFowbm5QbUVCRkYya3FmaXhKVDYwd2dkVEpycXpBMTdFOFN1ajM1SlhBRkVmTQpKVUdjaWpXbTVBR28xSTZuNlhSbE9jOGlPU2VmS3dJbEYwWGpQT1R3VzVSZ0hOZ0xyTU9seFNXV1J3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNdk9rTFZiakxGb0tieW5RMmpVUUVNVQpDazlGTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBejJOWmNkQlQrOHZXR0dDTkZFbzF4SnRIOU5acFZmZzdUCjlEemNmNWpGcktnZ1Z3bWpqS0F3dy9YRDBlRTVSNEdldDBLQXNlL2dWdE5HRDBjR1daQVgyNk9BdHU2SjRpR2QKakJvQUpxQjZLd3JIVnRJRWxXY1FnWmZFSTk4VWpIYUR0S2QvY1hlNVZXRmRSYUVLSkFieXVtbG9HekFMTEtpagpOVDNYUEd4NmdubFAzRkptM21uTDhQYjNjRis3bkVIZGV3dFRoU1FJZlNxSm9RYVMvMUFrcE04cURVZUlEQ21OCmFwWVlPQVBFRjFaUnA0ZWt3N2UwN1FVa0pBUnNmbHJyVzNpU2dTTE9ZZjJKaUVxOFNNN1VYL0F4cm9KY1dsUzkKRXpHeGluK1RXbko5QUlMVHpDSEdjdHl2QnFMVUJtbVR4a2x2L1EyMXRoa1orNjJxNkhiYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNUo2MmliS1NZN3FmOEc4SCs4S2xIMmZRaXcxUkFDdXkxUXhYbTQyanlGVzc1LzRkCnBTbnlPNTY3ZFRaTTRFWDY2aHdBK2k1SnVRQ1YvSGxCL0FETE8zR3ZrcW9ISHpwcTRtVnVpUEQ3SXB5dHFrRjMKdVQ0K09ySk9mNlNEY0RiOHR1MUNsaDFuUXdYaFVJNTBPbzNPdGlwdG5mVHRPRmRZNWhjdDhpTkFnSG4rT2FjcgpsRmI3NmxKOGNhZDMyKzZmLzVCRkR4dXh5cHZMS1E2cjB2bmM0TlF1WmhJY2R3TGYrOW95dVZwaEREYk1IbFhaCjBublBtRUJGRjJrcWZpeEpUNjB3Z2RUSnJxekExN0U4U3VqMzVKWEFGRWZNSlVHY2lqV201QUdvMUk2bjZYUmwKT2M4aU9TZWZLd0lsRjBYalBPVHdXNVJnSE5nTHJNT2x4U1dXUndJREFRQUJBb0lCQUNRaTdpbHZ2M0hpRXR2WApRUVRMYkh3OVZacFZIWU9RWkxFR1JXYkNDYXhsMk5DL3V3SGJVbjJZQm50dGZOTktYSEhhd1ZES05qNzIxNzVUCmtGbDc2cVBYd1cvR1RsL2lSUGpLSGFHcHJaaDMrWDlhMzhpNURPOE1OaG80NzhteDkxb1d3SnFueFNXejdUeGwKZC91MVpJSW96TERXQVJVUndXeUZKMjhKb1cxdERud3VubnhwMHZOY0tHSit1SzJvYUtxaTJOanBuczRJRHVDSApQR2dwQ202RnYyb1llZ1hqQ0hZNVl2VEZvbldBbnhJaE1rQWg0L2lpaTJqMjN1RnVNUUFLL3pRaVlWMDRvNTRqCmFjbmFNd0gyc1J1bWI5YzA2cy9MWkoxMEJZbWR5VEdnNXdrcVByQmUzWmpmZVc3RW16SXBsOFBLMnkxVzJ3VFgKWTNONUgva0NnWUVBK2R1RUJVdFM5RldKVDlPcGNndXZLNEJvcE5TQ2xOYmhXKzQ4SWpHb2VmK2FYVVB0RGFFZgo1eVcrZXNKUjk5WVFPVG9veituNmZ5ZFFqMnh5NDRCcllodmErdDY5dkJSb3ZmcEhOTmRJNGc3L0F2WEhHckJDCnA3RWtQMXJtWllWOUNWWGRnaDlIQm9XS0U2UDB1VElTb1g2SGpkcE9RTEN2VVk5aFVTaGpiRlVDZ1lFQTZqMkoKM1R1OHY3WTROeHFkeVdmdTFYZjVzcEpkenpDQUhWRW85YjBvZnlNbnVveTcya01xVHkwek1Qck1uLzhXcTFhagptZk4zWVB4YWNYS295Q0lIdUNzTVUvVFpyYzBHbEVHQUV5SmVzdHNDSTR1WXB3bDUrZklsZkY5TktJZDBtVlBBCit6aS9uZVh4RXp0bm5aeUxLVUpKZDlLV28wa0VSRXFsM1FmTTFDc0NnWUVBa3FockFjQ0kzS29vZ3hhMmF4NjQKbjB3c0lEUXN3Yml2WndxYmVXYTBnWWVxei92QzlURVNUTmMyeTArc1ZWRHRET282Y20vZ2ZTcFNleDBwQXFpcQpYMWdDWFNiSkw5QzYrbWdoeTc1aUpXNnYrTWpUS2JNMExNSXBpSmFPamlDZ21BNHlpdUpaQ2xid0NUOC9za1RWCjhyMFdUQWxMeldUb1EzTnBwLzJRL2xFQ2dZRUFoeUFFM2JqT1E1R3NrQzBzaExrT0Q5cnNFbFZaQkdLb0pVRmkKYlpBM1FsQlhaTWcydmN3dEpndWZFa3c3cXJpT3JUeUhtQkhZOWZ2ZGVNQjZHU2w0Wm9kK3p4ZmFVdWFKT3hFbAovdU8rMlZKNXcyT09KaDNUWFpxUWdWVEF2L2FVRHJkQUJpeFFiWmZ1SC9nTzU5OGNjQ3FyRXhKS2o5dFpPTVFQCk5waC9VbzBDZ1lFQWdIN2V1UzVTNjVCQVVYVVZ4eExvNzg4dkl4bFN3MExnZjdPWFlWSERyam5Ha3B4UWJUSWcKRmh3aWN3amJFajFIOHhKNlRpamk3Q2V3Z1AwZmIrT1BqVXVCMGxRQ1NHdGtab0d1ZVhqMFVucEc5Q05rOExHYgpxMk5uL3dUc0h3QTB0bnVNWW4yOGsxMEJodTF6aWNXNmRNUEJISUNlc0w0ZDhyb0p6eHRBSldVPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lSQU1pWStleHpMbm1PdE9lZnI5Ym5MMk13RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUmEyOXVaeTFoWkcxcGMzTnBiMjR0WTJFd0hoY05Nall3TkRFM01EZ3pNREUwV2hjTgpNell3TkRFME1EZ3pNREUwV2pBd01TNHdMQVlEVlFRREV5VnJiMjVuTFd0dmJtY3RkbUZzYVdSaGRHbHZiaTEzClpXSm9iMjlyTG10dmJtY3VjM1pqTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKcVZrVmswVkdpdXFudnNFVTl6bE12N0c0VFdkUnh1djY5MVpkYjdzM3VuOEtINlR0ZUpqakhyci9mYnliN2pTMQppUmZXQUhFTEh5Vk5LUVRBY0ZXOE5uejZhUWRnUWxvUmJtYXZrcm9yYVN2SlZ3cVlkenY3ZWtpaXcvUVkrTHZrCkNpU0FLZ0UzbUhGbnlSdUw5QkJ5eXVXUTEvNEZ5QXJGbXR2bzNVMzEyR09CZ0lLN0I2Q3hMSXNzRUpqRlNtTm0KQXhrWGdIUk9pMklVVEs0K2Z6am9uaS9LNUVuenZ1THB3YzM1ODYyLzY3cmhzdDlycDBjdkxnN01nSFJOVWl0bwpUV0l0NmVIblcvOHNaVW8xd1BIYWRFVU0reDVIUnhvalVVUXdzZkFZakhWNmFtUWQzZ01zWUZldXlDT1R0UHluClpwejdIVFNpQlpXS1pzSklaK0s3VVFJREFRQUJvNEdUTUlHUU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlYKSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRQpHREFXZ0JUTHpwQzFXNHl4YUNtOHAwTm8xRUJERkFwUFJUQXdCZ05WSFJFRUtUQW5naVZyYjI1bkxXdHZibWN0CmRtRnNhV1JoZEdsdmJpMTNaV0pvYjI5ckxtdHZibWN1YzNaak1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkoKZmpKaVZzbVZ5NGtqZS9QNzh1YkZQNWpOcnQ0Sjd5K0pMM3JqamlvLzYzelErbkJPOU82TW14Y0dqVWhYODU5YwpYc0hTY2V2RUpIR2J6S0Vnbys4ZmFDWU12VTY4YjVNek5WTmxiN3JSdkdmNWlFYVRsZWRhM0YrNHgxck9tYXhFCk9Sai9mcUlMcFlPR0VKZE5vRUVhelR6eE5zL1k5ODZJRHh5UUFPY1J2VC9yc0FEd2JRM0I1bVA1TDlvRGp5WkcKc3UvdTNUeFN0Y3YvcENodGZkeHFPQjY0dmNYR3JzVTIyNkRIdUFvMGhCeE1JdVBXQmliZUV3V0k3U25sWWEyUQoxc2l0NU54VlV6VmUzYVdEODZzeFlzelV1VmljN2N3SFYrajRkbXVLVFpZUHB3NTMyMzVVa2NaVG1XNDl3aW82Cms3YS9tK1ptWjhIRm8ydERvSFYvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcVZrVmswVkdpdXFudnNFVTl6bE12N0c0VFdkUnh1djY5MVpkYjdzM3VuOEtINlR0CmVKampIcnIvZmJ5YjdqUzFpUmZXQUhFTEh5Vk5LUVRBY0ZXOE5uejZhUWRnUWxvUmJtYXZrcm9yYVN2SlZ3cVkKZHp2N2VraWl3L1FZK0x2a0NpU0FLZ0UzbUhGbnlSdUw5QkJ5eXVXUTEvNEZ5QXJGbXR2bzNVMzEyR09CZ0lLNwpCNkN4TElzc0VKakZTbU5tQXhrWGdIUk9pMklVVEs0K2Z6am9uaS9LNUVuenZ1THB3YzM1ODYyLzY3cmhzdDlyCnAwY3ZMZzdNZ0hSTlVpdG9UV0l0NmVIblcvOHNaVW8xd1BIYWRFVU0reDVIUnhvalVVUXdzZkFZakhWNmFtUWQKM2dNc1lGZXV5Q09UdFB5blpwejdIVFNpQlpXS1pzSklaK0s3VVFJREFRQUJBb0lCQUFGc2ZWRHlxU2dyMXVNMApybDl4dk9KenRRLzVpV2Q1dm05cjYzY3dCTVR0b29Fbm10T0R2WTBabDJKUVBxTmZFQk9wL3FPY1Q3S2dWcWk4Cm9IMlJTdmJPVURDbjNqaFFsNHJ0RkJiUXQrSzNlb2JmME81WHM4S1FiOFhqL0gzQzNxVHpMNXlxeS9QZEtEazUKb1JDWlBzM1Q1a2Jhbk9QVXExcWs5SzAvcFl4L0xpcXlxMGYvQktHS3F0cXpUcDExVkU2VVlvWWZ3TVZKWCsvMApYbVJMdVpuZFBCOXlkczlkNVN2QW1oSllBS25tbFczdjVTRXRZZHdtOUZnY3lsZHkzQkVUTWdrL1VSaW5jUEhiCjFIMG01ZWZ3MS81dWVpdWovZmNLdlBTdFdiaXU0SlVTZGY1UDZ2WEJibFJGbjBtdjdUZkhIOGtLelE2cHZLdVQKc2pBMHlBRUNnWUVBM052Y2p4ODFoZTAzYUU1K2ZRREZaQXFsVVlXU2p6NGorOEM1V3FsYm9XTnAzbjRpbEREdgoyTGFPR0N6YjlzTmFIYWJWcUMzMTFtS2ZXQllOOWlTK0E3bVJhRXJqUURtTXZadFBMWS8xVjdFUW1mbHFiODVkCnN1OExqQzYwOW8wQkRobEkyTzNEMWtmTEtYcGVXZ1hnZERSR3J2ckkyT1V3OUVhUHkwZkNsWUVDZ1lFQXhFc08KUVBpS2VKTy9Yc1JaeVk3ZXNwQ0YyRlAxVDAvMmNTSlpGYlJic3pXOUdoUWNHbWY5Q2NZZzFiall3R0FFSjdJMwp1cHphMnFNWnZHWW4zekp4eks0dExYenFET1hNU2ZJS3F0QXE4ZUVPWWJBdFNpenQzdkhzY3BzL2wvNC9WWk1QCm42U09xSHZMTkNLVmt6Vy9Vblo1ejRxdmtvMDFDcGpUV2xNL0xkRUNnWUVBMTJtMklQNHVwUmF1MFJTbU9HUDEKSXROalZUVHpzclRJUWZkQ2toUFhKSDBqT0hoTVg3K3ZYKzhHZnJ2YU96OWtlTUZOYVFDUzQreERRSllhUGZhdQpRbEhQYWlxSXBnNjduLytJWlljZ284dzJ4Z2RIOGc4VXdyNTJ3OTZXY0ZjdExVUXFFak10cktWUG1ZQVo0TElVCnJ5S0J3bzhtTUs2eVpiOGc1d054M1lFQ2dZRUFxaTJ3RTkvbW5SYnF5TXhPVTVLTHZCL1VDbkx2c0cxUTZWQ3cKRDBNb1pUeG56OTR6WnlsVWxVNnlWTmhIQXJHN3FIYTRIZyt6SmU1VmQ2TFJXbzR2WHhaNmtIOUZveHp2ZWdSZgoveXN1c0RrLzhLMSs5bG54ZUdJaGJsTHVWV1hWbnVrNm1GdGdXdTNJaEZDZmdOc09IZjRkS1RQQmQ3cjRpMUZuCm0xMmszcUVDZ1lBZlpwZ1BuSThCVkxFZytYUXRDTHpjcWNnOG9wOHphMjI0OXFXOXlKQkFhbGp3TTRpY0lVM0oKKzB6eXhhamFFZmpFWnF1eWlNajdGRmhicnBaNUUwdUVQQmtMSVhZdThJeXQrWm5xcVJnWTBXSTRhcnh1c0pxVgo4YlJtVWVGd0pSamVyaElYdUZERXp5T1JVbk9RdWN5Tmwxd3NqKzFsZldBOUFYLy9aR25qeGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-kong-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: kong/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-kong-kong-validations
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRTHIzUDR1bzFEMDBuNjQ2QmJLNSszakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd09ETXdNVE5hRncwegpOakEwTVRRd09ETXdNVE5hTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVKNjJpYktTWTdxZjhHOEgrOEtsSDJmUWl3MVIKQUN1eTFReFhtNDJqeUZXNzUvNGRwU255TzU2N2RUWk00RVg2Nmh3QStpNUp1UUNWL0hsQi9BRExPM0d2a3FvSApIenBxNG1WdWlQRDdJcHl0cWtGM3VUNCtPckpPZjZTRGNEYjh0dTFDbGgxblF3WGhVSTUwT28zT3RpcHRuZlR0Ck9GZFk1aGN0OGlOQWdIbitPYWNybEZiNzZsSjhjYWQzMis2Zi81QkZEeHV4eXB2TEtRNnIwdm5jNE5RdVpoSWMKZHdMZis5b3l1VnBoRERiTUhsWFowbm5QbUVCRkYya3FmaXhKVDYwd2dkVEpycXpBMTdFOFN1ajM1SlhBRkVmTQpKVUdjaWpXbTVBR28xSTZuNlhSbE9jOGlPU2VmS3dJbEYwWGpQT1R3VzVSZ0hOZ0xyTU9seFNXV1J3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNdk9rTFZiakxGb0tieW5RMmpVUUVNVQpDazlGTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBejJOWmNkQlQrOHZXR0dDTkZFbzF4SnRIOU5acFZmZzdUCjlEemNmNWpGcktnZ1Z3bWpqS0F3dy9YRDBlRTVSNEdldDBLQXNlL2dWdE5HRDBjR1daQVgyNk9BdHU2SjRpR2QKakJvQUpxQjZLd3JIVnRJRWxXY1FnWmZFSTk4VWpIYUR0S2QvY1hlNVZXRmRSYUVLSkFieXVtbG9HekFMTEtpagpOVDNYUEd4NmdubFAzRkptM21uTDhQYjNjRis3bkVIZGV3dFRoU1FJZlNxSm9RYVMvMUFrcE04cURVZUlEQ21OCmFwWVlPQVBFRjFaUnA0ZWt3N2UwN1FVa0pBUnNmbHJyVzNpU2dTTE9ZZjJKaUVxOFNNN1VYL0F4cm9KY1dsUzkKRXpHeGluK1RXbko5QUlMVHpDSEdjdHl2QnFMVUJtbVR4a2x2L1EyMXRoa1orNjJxNkhiYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRTHIzUDR1bzFEMDBuNjQ2QmJLNSszakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd09ETXdNVE5hRncwegpOakEwTVRRd09ETXdNVE5hTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVKNjJpYktTWTdxZjhHOEgrOEtsSDJmUWl3MVIKQUN1eTFReFhtNDJqeUZXNzUvNGRwU255TzU2N2RUWk00RVg2Nmh3QStpNUp1UUNWL0hsQi9BRExPM0d2a3FvSApIenBxNG1WdWlQRDdJcHl0cWtGM3VUNCtPckpPZjZTRGNEYjh0dTFDbGgxblF3WGhVSTUwT28zT3RpcHRuZlR0Ck9GZFk1aGN0OGlOQWdIbitPYWNybEZiNzZsSjhjYWQzMis2Zi81QkZEeHV4eXB2TEtRNnIwdm5jNE5RdVpoSWMKZHdMZis5b3l1VnBoRERiTUhsWFowbm5QbUVCRkYya3FmaXhKVDYwd2dkVEpycXpBMTdFOFN1ajM1SlhBRkVmTQpKVUdjaWpXbTVBR28xSTZuNlhSbE9jOGlPU2VmS3dJbEYwWGpQT1R3VzVSZ0hOZ0xyTU9seFNXV1J3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNdk9rTFZiakxGb0tieW5RMmpVUUVNVQpDazlGTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBejJOWmNkQlQrOHZXR0dDTkZFbzF4SnRIOU5acFZmZzdUCjlEemNmNWpGcktnZ1Z3bWpqS0F3dy9YRDBlRTVSNEdldDBLQXNlL2dWdE5HRDBjR1daQVgyNk9BdHU2SjRpR2QKakJvQUpxQjZLd3JIVnRJRWxXY1FnWmZFSTk4VWpIYUR0S2QvY1hlNVZXRmRSYUVLSkFieXVtbG9HekFMTEtpagpOVDNYUEd4NmdubFAzRkptM21uTDhQYjNjRis3bkVIZGV3dFRoU1FJZlNxSm9RYVMvMUFrcE04cURVZUlEQ21OCmFwWVlPQVBFRjFaUnA0ZWt3N2UwN1FVa0pBUnNmbHJyVzNpU2dTTE9ZZjJKaUVxOFNNN1VYL0F4cm9KY1dsUzkKRXpHeGluK1RXbko5QUlMVHpDSEdjdHl2QnFMVUJtbVR4a2x2L1EyMXRoa1orNjJxNkhiYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRTHIzUDR1bzFEMDBuNjQ2QmJLNSszakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTVRjd09ETXdNVE5hRncwegpOakEwTVRRd09ETXdNVE5hTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTVKNjJpYktTWTdxZjhHOEgrOEtsSDJmUWl3MVIKQUN1eTFReFhtNDJqeUZXNzUvNGRwU255TzU2N2RUWk00RVg2Nmh3QStpNUp1UUNWL0hsQi9BRExPM0d2a3FvSApIenBxNG1WdWlQRDdJcHl0cWtGM3VUNCtPckpPZjZTRGNEYjh0dTFDbGgxblF3WGhVSTUwT28zT3RpcHRuZlR0Ck9GZFk1aGN0OGlOQWdIbitPYWNybEZiNzZsSjhjYWQzMis2Zi81QkZEeHV4eXB2TEtRNnIwdm5jNE5RdVpoSWMKZHdMZis5b3l1VnBoRERiTUhsWFowbm5QbUVCRkYya3FmaXhKVDYwd2dkVEpycXpBMTdFOFN1ajM1SlhBRkVmTQpKVUdjaWpXbTVBR28xSTZuNlhSbE9jOGlPU2VmS3dJbEYwWGpQT1R3VzVSZ0hOZ0xyTU9seFNXV1J3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNdk9rTFZiakxGb0tieW5RMmpVUUVNVQpDazlGTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBejJOWmNkQlQrOHZXR0dDTkZFbzF4SnRIOU5acFZmZzdUCjlEemNmNWpGcktnZ1Z3bWpqS0F3dy9YRDBlRTVSNEdldDBLQXNlL2dWdE5HRDBjR1daQVgyNk9BdHU2SjRpR2QKakJvQUpxQjZLd3JIVnRJRWxXY1FnWmZFSTk4VWpIYUR0S2QvY1hlNVZXRmRSYUVLSkFieXVtbG9HekFMTEtpagpOVDNYUEd4NmdubFAzRkptM21uTDhQYjNjRis3bkVIZGV3dFRoU1FJZlNxSm9RYVMvMUFrcE04cURVZUlEQ21OCmFwWVlPQVBFRjFaUnA0ZWt3N2UwN1FVa0pBUnNmbHJyVzNpU2dTTE9ZZjJKaUVxOFNNN1VYL0F4cm9KY1dsUzkKRXpHeGluK1RXbko5QUlMVHpDSEdjdHl2QnFMVUJtbVR4a2x2L1EyMXRoa1orNjJxNkhiYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
