---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5uNmZacEtFOVo1NHJYdWtkWlB0REFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTWpBeE1EQXhNakJhRncwegpOakEwTVRjeE1EQXhNakJhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBlRjlpWEI1ZDN1V2dnY3dTWCswKzdFQjg5WTYKc1c0bld3bGZnNG9HN09IaHNGcEJWQVM4MEw1ZitmQnBJdjJxYnNDb3RIZ0g3TWR5akVMdkdaenlta2ZySXIwUAptc1VLNklJNytuV2podStEVGZueldWS1NKd3J6bFJmN2NMNmR3TlJ0bkJWbHFNVkVKWUY3cno5OXJ6VW1OK1hNCkdUM1EwYWQ4L0RnZmF0Kys5RFY1Z2x5M1JoN2o3d2NNUnZ4VXgxbGdmS3FrQmROcTUrLzNQV1p2cC9LNTdFTTEKRmZobjVKWTVRUjlxQ3poU3ZUMnIycG9BaGw1NTBhTFBxVVM4Y1kxejRTa2lWQVl2eU93OWdxcHk3VmZYK3EwOQpTRFdMMzhYb21rd0I0bHNJSURDR2IvSFg1TU15WktnL2NQQmhPRzNRTmMrSTNrR2h4ejhxd0FkSXdRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHUnpGa1lzZmE0MnZNcDBSbm41dnBOZgpVRTBUTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT1ZKMkE2UmxlNW1WVU9HTXJUOWdmTWY2TFhRU2dJak5WCmdEVUt6L1BYZTFDWmxhZUEyR210bS9OSTlmSXY4bGxHam5qcUhvQm5qblVxN1UveXRnbUpHenhlQ3lHS1h3MGEKa0FQOUZPUWczTDZuY1I1bDB1dmtxd0lxenAzcmJKR1d6SjBMMjhXaUhZbW85NEFXeW9CL083RzVXV1NGQUNPRQoyaXUxMGs4ekNiVUUxYWFBbnpxZUhPSVV6WnhVV1pwWk5oQTQxZ05NWXdiTDFrbDNjM1ZjTzJJQkdpeS83ZDY4ClUxTGFXaXJIMi9rTUtCNUdLU2JlRk5yVWlBTklqQktPaGlYbzcraENmY3JjMWNsOVN2aWc4OTV3NnQ5ZzdkYVgKRUE2UjdYc0orajBQK1c0cnFLZFVDeUhvU2g2a2M4dWR5ZGd4MUxXM0VyRHk4Y1padVZ5RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcGVGOWlYQjVkM3VXZ2djd1NYKzArN0VCODlZNnNXNG5Xd2xmZzRvRzdPSGhzRnBCClZBUzgwTDVmK2ZCcEl2MnFic0NvdEhnSDdNZHlqRUx2R1p6eW1rZnJJcjBQbXNVSzZJSTcrbldqaHUrRFRmbnoKV1ZLU0p3cnpsUmY3Y0w2ZHdOUnRuQlZscU1WRUpZRjdyejk5cnpVbU4rWE1HVDNRMGFkOC9EZ2ZhdCsrOURWNQpnbHkzUmg3ajd3Y01SdnhVeDFsZ2ZLcWtCZE5xNSsvM1BXWnZwL0s1N0VNMUZmaG41Slk1UVI5cUN6aFN2VDJyCjJwb0FobDU1MGFMUHFVUzhjWTF6NFNraVZBWXZ5T3c5Z3FweTdWZlgrcTA5U0RXTDM4WG9ta3dCNGxzSUlEQ0cKYi9IWDVNTXlaS2cvY1BCaE9HM1FOYytJM2tHaHh6OHF3QWRJd1FJREFRQUJBb0lCQUEwYnk2cmZ5NG1JcDdVdwowajBNcllXeVVFQXZyc1cwdWNGMDlTcFU3d1VyT0lXU0xGVnlabVZzbGZNUGI0K0hVaitjVS9pbS82RlRoWmJWCjkwVWo1UHdTTU4rMjV4UEkvSHF4U0FJYjU4ZFRDQ0pTWFV1eXZiLytHbyt1ckgwVll5d0kzWHlYS0VoMUJsU2MKYmVURWRLOHkyUWxUekpRMkVWbHdEZTEwbGU4QkRPaTZtSXgreHp4d1FUS0lBbVExdFRGTkh2cGVxYWlRb1ZNTwp1RHIrcXd3VzFkbTdmTGtjRmYrWWxGYm1iQXQ5aUFwU1VjMDk0S2xKTEJFV2hTR3Rxd08ycnNwWWduY0I2T1lrCnBXbEIxT1B4UFhuZG0wU0lZRWRuRkdtOWwya05relk0cTlRWXdWM1o4VmxQdlFnQ2ZoZ25sZCsveWJhUmozN3oKODlyTVJKRUNnWUVBMEQ4dDFYQ2lvd2Y0bHlxY0YvdCtJUkpjUHQ2R2N2RTU3Sy9zTitzdWVVcU0xM09JUm80VAo2dVkwdnpjeExQYzlXV0hlNzBnQm9ySEV6c2hzOXNVK0NUMHU4UWpFVmpiUU9WWi9xR1hna28ySCtOSjlKak9ECi8xdTJuVGNyTE85cnRiV1l3SDZSQTZ4MzFHNUE4aHNpdk1jZGN6dWk3b3RrdnJoMmtwNEJ5RjBDZ1lFQXkrdEgKaW1rTjRIcDYyQVh6eUFzNmd3clZlVzVvekxtN2RRcEtFcE40dzNhcHFCMmRBUDBBcUlJVmpnak9OZDJVRlVyWApyOHEyNjFkelpEMGg5eUhmbmFKUlBTV2pmQUxsTXJNelVJNnFDVGNHaFdMYmpyNnp5RlpxOHBIVytiRjlYeTN5Cmt3cUNhek1qYXRudFk4bjgvZFNKV3VKMjM3VFNBbEpoMW9iQks3VUNnWUVBajVzaDlsQ0lOemtsK3NqTmY5UlUKZEdYKzZ2UDFiNHBlVVpRM3A1QXRLa040d0pMUlpTWlJJZW5DY2lLVGJOakttN3JjUzlJeUhvbk1tSFNxZjdvaApQNm5MbHpoZWZMMnI5ZjVxWml4ckkyVXFZVEoyVDBPelFRTnorUkswV1haNXBvTW1aWWhpWkZBcENudEZtaStRClV2SlVvc1I3WlZrSERtYVNqaVVjUVprQ2dZRUFtSkVTdUhxN0dDMXJCWDhHa3EvYitqazcySnVEcTFCMjhTMWUKbUNGZjVCWSsvdm9SQXJGSU1jc0o1M2V0R040TU1oWUo0NHR1YWd2RzJNTm9TeWM3MEF1bWJuSmZxNlBhNmFEcgpqcVQra09CcmI1YTBJRXVMNVNMSzUydTRCSjhINXhOUWZ6VUl1TDNORE4rNTNjUTlGWWhUci96cDVadTYyR1BjCnNZMm1yMVVDZ1lBdWdFbkF4N3NyK2kwTnhwaDFaamswOGlaM1Q3cTNXdFVjdnhrSzdYWmdLbGVKQ2dCRHkyczEKY2hQVGtWczR6UVlGWTdmM0doNmxjV2pnaGlzbzRsT2lQbnZoR2xnbXVuREVKSlF6N1BObTJ1MkxDUE4wc0RDSgprRUttaDhleEY4TE83QzN3RTJBcmJ3OXFrM0w0UmgvMlpScEYveVkxSXl6VTZ6M3ZEOVk3ZkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-kong-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lRTVRlclVjMDM3Y1BWZlE1eUQvODFXVEFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTWpBeE1EQXhNakJhRncwegpOakEwTVRjeE1EQXhNakJhTURBeExqQXNCZ05WQkFNVEpXdHZibWN0YTI5dVp5MTJZV3hwWkdGMGFXOXVMWGRsClltaHZiMnN1YTI5dVp5NXpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRG0KU2E0ZGxvUGtFa1dFUXlhSVZ6OC9rV3ozd3ZDakdSUHVOczlhSjJudVdhSFZCNkFXZFdjMExTdG9Gc3huUWppQQpTMW5aME43QU5NTnU0TnNwTS9uZGE2VStmY2lPQUxwcHNodVhGTTVvWG9oSTlRTzNUL25FQlZodFFvWkZJaFZtCkxlaGZIYWZ5TmYwVHRnVHV0bHQyT3g1elJoSkVEelZ5eTYvYXExZW5HWHZEdXhZR0tNYnVhTEhaS2dtcm9yQXAKU2dtNUxualhDOUJEOVowY0dZRVZlV2RLWDBMNTFvUmJ4dWhjWWtScU1aMU5xeU5ObkVqRGsvZ2VVdXFKR3IvNQpzY3RhK09lWVg3aVBzcCtScjYyaCtkV2ZmYUVObTdkR3JoU1pTSFovalg3YVhIeXg4dmVEeEx4dTZMZWlLVVdrCjB6WDlOa2l0RDVpMzg5WWFielAvQWdNQkFBR2pnWk13Z1pBd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkSXdRWQpNQmFBRkdSekZrWXNmYTQydk1wMFJubjV2cE5mVUUwVE1EQUdBMVVkRVFRcE1DZUNKV3R2Ym1jdGEyOXVaeTEyCllXeHBaR0YwYVc5dUxYZGxZbWh2YjJzdWEyOXVaeTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCaVEKMzl6M0pTazFDbmVSN0RWT2oxcFVjUms0bno5Y09KUWxhTXUySmVQTTV5VUY1UmFHWUFlQ2FlcGtsajdGZ0xKMgpNNWVCNENsaUJpTjBXZm5BMHN4SGhKbFQrZXN2WW1EU1BaL2NrWi9hTlNCWkhobnlrakVKb0t0bjVXeXlVaHh6Cm16dDNRREpGaW1vd016aVR6bXFpTGJjWFlGNlc1NWsyaGpGdGJJazJacmEzRDk0endmSDNjZUxnTGQ3NmVMWEgKdzdKeVc2WE9HOUdIZFFEOU5Fd1VFanB1a1ZKSzI1dytVRHByWDhUdDRyWVdYNEZDZjdsb2s3Qmg1UUJUSVBzcgpFaER4QlEvZFp2Z3c1YTV2cFQycXprRTErdE1KZWZRWjFCaUpkY1F1YUdIbU5Cc0NwcVhJVmNONGI5S2xSQ200CjczeU81NWlaTVlBa1c1OUo3ZG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb1FJQkFBS0NBUUVBNWttdUhaYUQ1QkpGaEVNbWlGYy9QNUZzOThMd294a1Q3amJQV2lkcDdsbWgxUWVnCkZuVm5OQzByYUJiTVowSTRnRXRaMmREZXdEVERidURiS1RQNTNXdWxQbjNJamdDNmFiSWJseFRPYUY2SVNQVUQKdDAvNXhBVlliVUtHUlNJVlppM29YeDJuOGpYOUU3WUU3clpiZGpzZWMwWVNSQTgxY3N1djJxdFhweGw3dzdzVwpCaWpHN21peDJTb0pxNkt3S1VvSnVTNTQxd3ZRUS9XZEhCbUJGWGxuU2w5QytkYUVXOGJvWEdKRWFqR2RUYXNqClRaeEl3NVA0SGxMcWlScS8rYkhMV3Zqbm1GKzRqN0tma2ErdG9mblZuMzJoRFp1M1JxNFVtVWgyZjQxKzJseDgKc2ZMM2c4UzhidWkzb2lsRnBOTTEvVFpJclErWXQvUFdHbTh6L3dJREFRQUJBb0lCQUFyZllhMjBWN3I4VGR1RwpLT2ZGenNJT2trTVhqN0ZhQnNIZVJRRWpRdGgvYk54aytGNzNGSFFkbHFMYTIrZE9qaFdPK1RBSFNyblZuWUNICnB6NFZYZSt1SEdhTVVJK0lsbmU3Y21nSEVnMVNPdDFvakFOZU8zbWRrdjQzTXo5SXZ0L21WcExmRUpLbktYM28KakxVUlYyN3VsemphZFhxM0lyVjYvbTBiS3crcVZaeWFiYk1yZVZLajRwVERRNGVDWmZCTHp2R0hhZ0lDYjhUbwpmZTRIRUdIMCtQVkRROU5oSCsrUWFaV1k4dVhQYyswTGJIRjVsQjM4VHNReWZNNE1YeEhaMHFSYTd1U08xQkprCkZaVE5JV3dpUW9hNVg4V21tWTkvaG5lOXJIWlFIL1QzS2c4SXR0TkF1K25kOTJhMEtFQ3RVdjFzcVkrMWQyZXYKd2hGK1FQRUNnWUVBK05ZZ2xKaWNmdEg2S0hVSHRDbi8wb0ZZajRaMGtVZUlURzdaT29QSUloMUVyRDcwZ3BvSQovWDJ6Zm9EajN6Z0d4QzBSTHRlZmNRaHVMVWlRWjg0MVBrQkFmZ04zZElpLy96WHBmRjRpQmVMeGpKUlF6NEVVCmoxbXRiaEZkVEtHdGhrZjg4bUhRNWsweEQzOUVLdG9uRkxPb21ockF3WExQVjl2TnFhdU1DZmtDZ1lFQTdPcmEKZDlTcjdiaXZicjhTdlRGU2w0bklSWlZtWllnWTBqUThLMEJybEtuQ2k5VTA4eFplOTFqa2didnBMcTA3YndDNApKV1ltZWRBUG84WnpCSzM5NHlzWXpQUnNldmFIVEUzR3NOcWFmbXc5ajkzVDV6RENsNWdQS2tYN3VoZWIxMEZJClRtRXR4eFhBTk43T3lmdXdSU2ptSWF3TVJmd1pDendYbVd5eGE3Y0NnWUVBeEhCK0xmREFjcG1mUzdyL3h1bjEKRENDU1lsTzV5RXJaUGNXd2RiSTlGemxWMGtpc3pFRi80V1lQZ2ttTUd0Ym0rSTIvWitSTytYTzNUc1pmUWFPWApncnBFYjNhYklnTW0xdm1maGsvbHVoSHJzSmdScDQ1MlJhaDg4a3lCQkJNS290eEh3cTBYdGdld09GUzI0c0Z2CllyZGwzYXBMQ3l4d3BTSmZuSmRScVRrQ2dZQlB0K2F6RTVpV2NPSjIvVXdzNVAvSmhjOGh1dGV0cWxIUHlVdkYKc2ZPQkhtNGI1eTNkN2RVZW5ZYW1NTGlSd0RDVGRVYUJMeEliUXV0QVRISS9UTngxSi9jOFg3SnczYXRBL1pxeAp2NXprbFQ5UnZXNmtDRUF5Q2pSd0lRUkc1ZExHWjIwUkVwbjR0MVRwZFY5WGo1ME1hR3FuUWVFUFczaUIwMEtOCm1ZbEptUUovSmxydDNUcXdZN0VJTlRkK1N6YWpOVFVTSTEya3l0UTBhTWpWN2JpbGdGTjJ5eW9hdlF4M3F0elUKaWw3Ri9aZXdwejZSSFhsTWczR2I2RFkzYlptajBxOU1LdmpxeVdLMjNxRmxLR043OEFmb1d3Tkd2RGhEc1N1QgovaW90U2RiK3l1N0lxbjY4MHNhN2p1bjVtVTFlMkVvbFRZTnZvOVRCWXNiU1l1UEZUQT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: kong/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-kong-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: kong/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-kong-kong-validations
  labels:
    app.kubernetes.io/name: kong
    helm.sh/chart: kong-3.2.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5uNmZacEtFOVo1NHJYdWtkWlB0REFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTWpBeE1EQXhNakJhRncwegpOakEwTVRjeE1EQXhNakJhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBlRjlpWEI1ZDN1V2dnY3dTWCswKzdFQjg5WTYKc1c0bld3bGZnNG9HN09IaHNGcEJWQVM4MEw1ZitmQnBJdjJxYnNDb3RIZ0g3TWR5akVMdkdaenlta2ZySXIwUAptc1VLNklJNytuV2podStEVGZueldWS1NKd3J6bFJmN2NMNmR3TlJ0bkJWbHFNVkVKWUY3cno5OXJ6VW1OK1hNCkdUM1EwYWQ4L0RnZmF0Kys5RFY1Z2x5M1JoN2o3d2NNUnZ4VXgxbGdmS3FrQmROcTUrLzNQV1p2cC9LNTdFTTEKRmZobjVKWTVRUjlxQ3poU3ZUMnIycG9BaGw1NTBhTFBxVVM4Y1kxejRTa2lWQVl2eU93OWdxcHk3VmZYK3EwOQpTRFdMMzhYb21rd0I0bHNJSURDR2IvSFg1TU15WktnL2NQQmhPRzNRTmMrSTNrR2h4ejhxd0FkSXdRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHUnpGa1lzZmE0MnZNcDBSbm41dnBOZgpVRTBUTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT1ZKMkE2UmxlNW1WVU9HTXJUOWdmTWY2TFhRU2dJak5WCmdEVUt6L1BYZTFDWmxhZUEyR210bS9OSTlmSXY4bGxHam5qcUhvQm5qblVxN1UveXRnbUpHenhlQ3lHS1h3MGEKa0FQOUZPUWczTDZuY1I1bDB1dmtxd0lxenAzcmJKR1d6SjBMMjhXaUhZbW85NEFXeW9CL083RzVXV1NGQUNPRQoyaXUxMGs4ekNiVUUxYWFBbnpxZUhPSVV6WnhVV1pwWk5oQTQxZ05NWXdiTDFrbDNjM1ZjTzJJQkdpeS83ZDY4ClUxTGFXaXJIMi9rTUtCNUdLU2JlRk5yVWlBTklqQktPaGlYbzcraENmY3JjMWNsOVN2aWc4OTV3NnQ5ZzdkYVgKRUE2UjdYc0orajBQK1c0cnFLZFVDeUhvU2g2a2M4dWR5ZGd4MUxXM0VyRHk4Y1padVZ5RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5uNmZacEtFOVo1NHJYdWtkWlB0REFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTWpBeE1EQXhNakJhRncwegpOakEwTVRjeE1EQXhNakJhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBlRjlpWEI1ZDN1V2dnY3dTWCswKzdFQjg5WTYKc1c0bld3bGZnNG9HN09IaHNGcEJWQVM4MEw1ZitmQnBJdjJxYnNDb3RIZ0g3TWR5akVMdkdaenlta2ZySXIwUAptc1VLNklJNytuV2podStEVGZueldWS1NKd3J6bFJmN2NMNmR3TlJ0bkJWbHFNVkVKWUY3cno5OXJ6VW1OK1hNCkdUM1EwYWQ4L0RnZmF0Kys5RFY1Z2x5M1JoN2o3d2NNUnZ4VXgxbGdmS3FrQmROcTUrLzNQV1p2cC9LNTdFTTEKRmZobjVKWTVRUjlxQ3poU3ZUMnIycG9BaGw1NTBhTFBxVVM4Y1kxejRTa2lWQVl2eU93OWdxcHk3VmZYK3EwOQpTRFdMMzhYb21rd0I0bHNJSURDR2IvSFg1TU15WktnL2NQQmhPRzNRTmMrSTNrR2h4ejhxd0FkSXdRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHUnpGa1lzZmE0MnZNcDBSbm41dnBOZgpVRTBUTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT1ZKMkE2UmxlNW1WVU9HTXJUOWdmTWY2TFhRU2dJak5WCmdEVUt6L1BYZTFDWmxhZUEyR210bS9OSTlmSXY4bGxHam5qcUhvQm5qblVxN1UveXRnbUpHenhlQ3lHS1h3MGEKa0FQOUZPUWczTDZuY1I1bDB1dmtxd0lxenAzcmJKR1d6SjBMMjhXaUhZbW85NEFXeW9CL083RzVXV1NGQUNPRQoyaXUxMGs4ekNiVUUxYWFBbnpxZUhPSVV6WnhVV1pwWk5oQTQxZ05NWXdiTDFrbDNjM1ZjTzJJQkdpeS83ZDY4ClUxTGFXaXJIMi9rTUtCNUdLU2JlRk5yVWlBTklqQktPaGlYbzcraENmY3JjMWNsOVN2aWc4OTV3NnQ5ZzdkYVgKRUE2UjdYc0orajBQK1c0cnFLZFVDeUhvU2g2a2M4dWR5ZGd4MUxXM0VyRHk4Y1padVZ5RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
    - key: owner
      operator: NotIn
      values:
      - helm
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5uNmZacEtFOVo1NHJYdWtkWlB0REFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOakEwTWpBeE1EQXhNakJhRncwegpOakEwTVRjeE1EQXhNakJhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBlRjlpWEI1ZDN1V2dnY3dTWCswKzdFQjg5WTYKc1c0bld3bGZnNG9HN09IaHNGcEJWQVM4MEw1ZitmQnBJdjJxYnNDb3RIZ0g3TWR5akVMdkdaenlta2ZySXIwUAptc1VLNklJNytuV2podStEVGZueldWS1NKd3J6bFJmN2NMNmR3TlJ0bkJWbHFNVkVKWUY3cno5OXJ6VW1OK1hNCkdUM1EwYWQ4L0RnZmF0Kys5RFY1Z2x5M1JoN2o3d2NNUnZ4VXgxbGdmS3FrQmROcTUrLzNQV1p2cC9LNTdFTTEKRmZobjVKWTVRUjlxQ3poU3ZUMnIycG9BaGw1NTBhTFBxVVM4Y1kxejRTa2lWQVl2eU93OWdxcHk3VmZYK3EwOQpTRFdMMzhYb21rd0I0bHNJSURDR2IvSFg1TU15WktnL2NQQmhPRzNRTmMrSTNrR2h4ejhxd0FkSXdRSURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHUnpGa1lzZmE0MnZNcDBSbm41dnBOZgpVRTBUTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBT1ZKMkE2UmxlNW1WVU9HTXJUOWdmTWY2TFhRU2dJak5WCmdEVUt6L1BYZTFDWmxhZUEyR210bS9OSTlmSXY4bGxHam5qcUhvQm5qblVxN1UveXRnbUpHenhlQ3lHS1h3MGEKa0FQOUZPUWczTDZuY1I1bDB1dmtxd0lxenAzcmJKR1d6SjBMMjhXaUhZbW85NEFXeW9CL083RzVXV1NGQUNPRQoyaXUxMGs4ekNiVUUxYWFBbnpxZUhPSVV6WnhVV1pwWk5oQTQxZ05NWXdiTDFrbDNjM1ZjTzJJQkdpeS83ZDY4ClUxTGFXaXJIMi9rTUtCNUdLU2JlRk5yVWlBTklqQktPaGlYbzcraENmY3JjMWNsOVN2aWc4OTV3NnQ5ZzdkYVgKRUE2UjdYc0orajBQK1c0cnFLZFVDeUhvU2g2a2M4dWR5ZGd4MUxXM0VyRHk4Y1padVZ5RQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-kong-validation-webhook
      namespace: kong
