controller:
  existingSecret: vault-jenkins-secret
  admin:
    createSecret: false
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
  ingress:
    enabled: true
    ingressClassName: nginx
    hostName: jenkins.local
    annotations:
      kubernetes.io/ingress.class: nginx
