apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jenkins/templates/config.yaml
  - jenkins/templates/home-pvc.yaml
  - jenkins/templates/jcasc-config.yaml
  - jenkins/templates/jenkins-agent-svc.yaml
  - jenkins/templates/jenkins-controller-ingress.yaml
  - jenkins/templates/jenkins-controller-statefulset.yaml
  - jenkins/templates/jenkins-controller-svc.yaml
  - jenkins/templates/rbac.yaml
  - jenkins/templates/secret.yaml
  - jenkins/templates/service-account.yaml
  - jenkins/templates/tests/jenkins-test.yaml
  - jenkins/templates/tests/test-config.yaml
