---
# Source: common-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: "harbor.local/banking-demo/account-service:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: account-service-config
            - secretRef:
                name: account-service-secret
          env:
            - name: REDIS_URL
              value: "redis://redis.data.svc.cluster.local:6379/0"
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@postgres-postgresql-ha-pgpool.data.svc.cluster.local:5432/banking"
