---
# Source: common-app/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: account-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: account-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: banking/account-service
        property: database-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: banking/account-service
        property: redis-password
