architecture: standalone

auth:
  existingSecret: vault-redis-secret
  existingSecretPasswordKey: redis-password

master:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
