apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgresql/templates/primary/configmap.yaml
  - postgresql/templates/primary/networkpolicy.yaml
  - postgresql/templates/primary/pdb.yaml
  - postgresql/templates/primary/statefulset.yaml
  - postgresql/templates/primary/svc-headless.yaml
  - postgresql/templates/primary/svc.yaml
  - postgresql/templates/serviceaccount.yaml
