apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secrets/templates/cert-controller-deployment.yaml
  - external-secrets/templates/cert-controller-rbac.yaml
  - external-secrets/templates/cert-controller-serviceaccount.yaml
  - external-secrets/templates/crds/acraccesstoken.yaml
  - external-secrets/templates/crds/cloudsmithaccesstoken.yaml
  - external-secrets/templates/crds/clusterexternalsecret.yaml
  - external-secrets/templates/crds/clustergenerator.yaml
  - external-secrets/templates/crds/clusterpushsecret.yaml
  - external-secrets/templates/crds/clustersecretstore.yaml
  - external-secrets/templates/crds/ecrauthorizationtoken.yaml
  - external-secrets/templates/crds/externalsecret.yaml
  - external-secrets/templates/crds/fake.yaml
  - external-secrets/templates/crds/gcraccesstoken.yaml
  - external-secrets/templates/crds/generatorstate.yaml
  - external-secrets/templates/crds/githubaccesstoken.yaml
  - external-secrets/templates/crds/grafana.yaml
  - external-secrets/templates/crds/mfa.yaml
  - external-secrets/templates/crds/password.yaml
  - external-secrets/templates/crds/pushsecret.yaml
  - external-secrets/templates/crds/quayaccesstoken.yaml
  - external-secrets/templates/crds/secretstore.yaml
  - external-secrets/templates/crds/sshkey.yaml
  - external-secrets/templates/crds/stssessiontoken.yaml
  - external-secrets/templates/crds/uuid.yaml
  - external-secrets/templates/crds/vaultdynamicsecret.yaml
  - external-secrets/templates/crds/webhook.yaml
  - external-secrets/templates/deployment.yaml
  - external-secrets/templates/rbac.yaml
  - external-secrets/templates/serviceaccount.yaml
  - external-secrets/templates/validatingwebhook.yaml
  - external-secrets/templates/webhook-deployment.yaml
  - external-secrets/templates/webhook-secret.yaml
  - external-secrets/templates/webhook-service.yaml
  - external-secrets/templates/webhook-serviceaccount.yaml
