---
# Source: common-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: "harbor.local/banking-demo/transfer-service:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: transfer-service-config
            - secretRef:
                name: transfer-service-secret
          env:
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis-master.data.svc.cluster.local:6379/0"
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DB_PASSWORD)@postgres-postgresql-ha-pgpool.data.svc.cluster.local:5432/banking"
