replicaCount: 1
image:
  repository: harbor.local/banking-demo/account-service
  tag: "1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

configMap:
  enabled: true
extraEnv:
  - name: REDIS_URL
    value: "redis://:$(REDIS_PASSWORD)@redis-master.data.svc.cluster.local:6379/0"
  - name: DATABASE_URL
    value: "postgresql://postgres:$(DB_PASSWORD)@postgres-postgresql-ha-pgpool.data.svc.cluster.local:5432/banking"

# Secret tự động kéo từ Vault qua ESO
secret:
  enabled: true
  vaultPath: "banking/account-service"
  data:
    - key: DB_PASSWORD
      remoteProperty: database-password
    - key: REDIS_PASSWORD
      remoteProperty: redis-password
