replicaCount: 1
image:
  repository: harbor.local/banking-demo/auth-service
  tag: "6"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

httpRoute:
  enabled: true
  host: banking.local
  path: /api/auth

configMap:
  enabled: true
extraEnv:
  - name: REDIS_URL
    value: "redis://:$(REDIS_PASSWORD)@redis-master.data.svc.cluster.local:6379/0"
  - name: DATABASE_URL
    value: "postgresql://postgres:$(DB_PASSWORD)@postgres-postgresql.data.svc.cluster.local:5432/banking"

# Secret tự động kéo từ Vault qua ESO
secret:
  enabled: true
  vaultPath: "banking/auth-service"
  data:
    - key: DB_PASSWORD
      remoteProperty: database-password
    - key: REDIS_PASSWORD
      remoteProperty: redis-password
