postgresql:
  image:
    registry: public.ecr.aws
  resources:
    limits:
      cpu: 375m
      memory: 384Mi
    requests:
      cpu: 250m
      memory: 256Mi
  auth:
    database: "banking"
    existingSecret: vault-postgres-secret
    passwordKey: "password"
    repmgrPasswordKey: "repmgr-password"
  pgHbaConfiguration: |-
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             0.0.0.0/0               scram-sha-256
    host    replication     repmgr          0.0.0.0/0               scram-sha-256

pgpool:
  image:
    registry: public.ecr.aws
  auth:
    existingSecret: vault-postgres-secret
    passwordKey: "password"

global:
  security:
    allowInsecureImages: true
  postgresql:
    auth:
      existingSecret: vault-postgres-secret
      passwordKey: "password"
      repmgrPasswordKey: "repmgr-password"