postgresql:
  password: ""
  repmgrPassword: ""
  resources:
    limits:
      cpu: 375m
      memory: 384Mi
    requests:
      cpu: 250m
      memory: 256Mi
global:
  postgresql:
    auth:
      existingSecret: vault-postgres-secret