postgresql:
  password: ""
  repmgrPassword: ""
  image:
    tag: latest
  resources:
    limits:
      cpu: 375m
      memory: 384Mi
    requests:
      cpu: 250m
      memory: 256Mi
pgpool:
  image:
    tag: latest
global:
  postgresql:
    auth:
      existingSecret: vault-postgres-secret