apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-rabbitmq-secret
  namespace: data
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: secret/rabbitmq
        property: rabbitmq-password
    - secretKey: rabbitmq-erlang-cookie
      remoteRef:
        key: secret/rabbitmq
        property: rabbitmq-erlang-cookie
