apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets
  - generated/external-secrets
  - generated/harbor
  - generated/jenkins
  - generated/kong
  - generated/postgres
  - generated/rabbitmq
  - generated/redis
  - generated/vault
