replicaCount: 1

auth:
  securePassword: false
  existingPasswordSecret: vault-rabbitmq-secret
  existingErlangSecret: vault-rabbitmq-secret

image:
  registry: public.ecr.aws

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

extraVolumes:
  - name: app-volume
    emptyDir: {}

extraVolumeMounts:
  - name: app-volume
    mountPath: /app

global:
  security:
    allowInsecureImages: true
