apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kiendo96/banking-gitops.git'
    targetRevision: main
    path: harbor/kustomize/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: harbor
  syncPolicy:
    # automated:
    #   prune: true
    syncOptions:
      - CreateNamespace=true
