apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq/templates/config-secret.yaml
  - rabbitmq/templates/networkpolicy.yaml
  - rabbitmq/templates/pdb.yaml
  - rabbitmq/templates/role.yaml
  - rabbitmq/templates/rolebinding.yaml
  - rabbitmq/templates/serviceaccount.yaml
  - rabbitmq/templates/statefulset.yaml
  - rabbitmq/templates/svc-headless.yaml
  - rabbitmq/templates/svc.yaml
