{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- if .Values.configMap.data }}
  {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- else }}
  placeholder: "true"
  {{- end }}
{{- end }}